// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FpZc+M2Ev4rKG4e7F3qsD1HopctRVLGqnhklS1nd2vkVcFkS0IGBBgA9BGX/vsWLh4iJctJZmoe9sVl",
	"kTga3V93f93gcxDxJOUMmJJB7zlIscAJKBDm1wTUAxefx/EUq7V+EIOMBEkV4SzoBcPBR0SYVJhFgMZD",
	"dBRHScs/aJEYUXwH9DgIA3jESUoh6AUPcNdaCs4UsLglQdyTCIIwIHq9VO8SBgwneiSzmy9IHISBgN8y",
	"IiAOekpkEAYyWkOCrcRKgdDT//sJt37vtn64PXL/tG6fu+G7k41/fvzP74IwUE+pXl4qQdgq2Gw2fjVz",
	"5JEQXNSPevXTAL3/vvseaXVRgplCoEciATLlTOozpIKnIBQBaecrTGh9pfMswawlAMf4jgKCx5RihvVL",
	"JFOIyJJESHGk1kQiHkWZEMCMirbk1jqzmq7vccPIbxkgEgNTZElAoCUXdkkrdWXhJRcJVkEvyARpCVjC",
	"zh2lwiqTDWeazabIvkQRjyuLEqbOTovFCFOwAqFXU0TRBuGv11wotK6qSWZJgsVTk1D2wfYqxo5Iv/MS",
	"AcuSoPcpGE9+6V+Mh4v+1Yebj6PJLAiDyeVs8dPlzWQYhEH/4mrUH/5nMfr3+Hp2HYTBdHT1cXx9Pb6c",
	"LIajyXikB91M+jez89FkNh70Z+bJeDIbXU36F/blL/3xRf/Hi1EQBj/1xxej4WJ6NRpcTobj2fhyEtwe",
	"rvRNGfuf7Fuvutt8NL/7FSKltXEOmDb5qn3ujSQJW1FQnGn88kxEdfymjS4/wIwzEmGK9HvEl0itobxI",
	"4elrK4mWH8eXjD553z0cVmWZG9Z+BRyunIQWEYVjVFZ1EceHpVYq+D2JQbTjKGkT3slPtNN4Lx41SxVJ",
	"mkAPEWexMYwWcg3ICYG8EFoNQkFclvjsXbe7c9OSp92DkGaf+rZbm9xlhMbIjy8r56TdbXdfPmIzXnMT",
	"uhBfbOAUUoNyGDy2MKStHFpFqJd6YWeL2zBIaSYwzUGhd8nhnacLwlYZxaIMS7ffgUbXB/s5uwPBQIGc",
	"ukHnxOVNHMdE6xTTacmLlphKCLd0PqVYaQC18nDvTS1BKcJWEh1pFYJUiDP6dFxzzYhmUoFYkLTBon5R",
	"NwiNp+ge0wzaaIAZugOE9W8S6xcPRK0JM3Dzwwfj4VU4Z/NgwhnMA5M41oBjClJ6QWWIdA5JiFIQmxE4",
	"U7yFpSQrlgBT7Tlrck3GY1ikXOxT2XM9cyT4kSQ6dp+dvn/3PgwSwtzvblfjv473qko+4lQHKr0x0txC",
	"6vw64TFM9ROjHImOzGIts8Vxe87+tQaGUgESmDJ6QowjwTNtoAWFe6AhigRgBbJYy7mTnq5nVIajuYfa",
	"PAh9qgeJCqUYTV5wHP+Iqc7rAt3h6DOwuKLOItRLoBApy1Z2KbNmg6pqLjRBQ34hrZcEq2iNFBYrUCjl",
	"sazvvGmQpXCNa4VVQ4ArBhS4FxnTzm8CPGjQWyplUd+eswFnChMmDUBxpDJM0c/fS69ml92NEWKEWZwv",
	"SJgFEeHM6u5w/+kXSIZYwzyTILzIEJfcqgnh8KgDFKYLkjbks5F7i8ZTqZdec6ksIGuW956GjpaCJ6ht",
	"A2iblsa0CVsJkPLTrY4QREHSbHH3AAuBn74IbKTWkY0DKY896psQ25ybZyXr5ihpNHKJxQ2sHYwZvP8F",
	"YVBWYimpVLJTY/4qhHRFT11O9yJnO0iACxCErRBuEj6n6DUImgMtmsnAjCQgFU5S9KCjkEa/Cx15qnjA",
	"sqSUPGTGWEHLLHoAFyHxFy3pEvx4AWylWeS7MxO1/c+T8PVV24un+ZxrX5/qOwHLoBf8rVOUtx1X5XW2",
	"Y9Um3EF2c9JouO5+0ig7O9TwMvtNIXpJZAc9ndyrhBlTerkMep8Om26nbW63pTLENP7TgKRYKmQX+qOo",
	"3KKPRjev5oa5SZ6LHsKmQhX9iKBCDd3Tw7mhn7ApwsYFkaquwCleEWbSFCWa1i1r+vM+JmuhgsGjWqR4",
	"BQvFP0MDiZ/pxyb8ClCCwL0OR9ZGjwrpmXpDATKjSjZlLf+q91ykkQPgVE8um93h9CMoHGOF93hZ4oaY",
	"o3hvi0wWrynFhCH5J1LYIJOKJ+gzPLUMA0QpJsImYoVXKxPRWYyWhCoQO9KZbVTtqqn0W3Q0nFy3Trpn",
	"b4vA+fq42HL//X1vI8vKI1Pc1BGa+Ffag0W1wqzmktc5qFHB7W6zX7vg1pxJPRO07S+teyPHrnTanrOx",
	"jrq6xLCkUPNm0x/adifDGixemxhgUkLjAUjPwatTha9ftjxc8/8YloQZNDokFVouU7R9O+p1fJhPCBvb",
	"OSd1Gudj0WLta9C9y1YKVm3Ecm3SEFMEXhqKbochM6xdrmHsAQVmUmukZWuco9lg2rkZTo9NCYnTlDrj",
	"uvHns9m0o/9ct9EQFIiEMLCm3EH95kzxFag1CFuFGasb1hWZsFYqnwhDVaVYy3vGWET3klwNHFEzZLP/",
	"opmuVohpqcV6lGRS6QK7pKTjhv1vX0x65e3DAqsee/vcbUcnbWC6vcq3/1zbblcOas/ZdDQZjicferkt",
	"HjAxQNBW9FUOAhannDCFKqW/6Z8WM4lE2vWwDdK2TgMcP+lqU8MLNIo02NpzNhxdjGajYTE559qMK7Tk",
	"mS+GvVKdnEEYmF2DMHBLNBo2d66X3Nc2NbYVVE/NjQlg6hsNto+jzWp5U5JRRVJqw5ZEWIDdEuIqoV4r",
	"le7tnzSUrZTyyBCMamNjq6oOy50aW9+a+rLqNxVpzk5Oz96Er+/KvNyVbD5J3pI0WsySuyrf/r67T5Z3",
	"b9+evS3JctK4r+CKR9xFvSXOqF5rNtClZHOeymcUwLPDb4ZTDbTCdPZxvQY3/ZQdtpv5ZotQiFt2fYej",
	"z9rbXAOmdPo/ff6tYGNEaoooB7Y4rXG3HMBNLTo9BlYWaqbZiBWmfFXzpz9Sw21ltjoF3ZirsiU3ZTdn",
	"Ckeq8F1T8E4F96feoqaj6xnqT8cmHCSYYcMLd1J3bb07WGO61BF2OPjYnrPZmki3BKX8QaL+yFyVsRiL",
	"2LKEiDNJpAIWPSEcCS6lnpu3gGzAoyQCJqEkeT/F0RrQqenKZ4K6wCF7nc7Dw0Mbm9dtLlYdN1d2LsaD",
	"0eR61Dptd9trldDSLVyOde9/Xq9a+FLH3l8EbMKAp8BwSoJecNbutt+47r4xXQenpHN/gmm6xiedvNrq",
	"PQcraPAAXTQhTOke1Zrkn9oyytyVZmlqWz55chnHbqlJUd2V77M/Pdcaw8ZtXJRxRZJJNxKlIEzp5O+m",
	"f8vAXD865Sf40dZkkvxuLjjy++g8orzd66knJkjud9Tdhd6e6q5J2lL1WBZ1m4aYvoDNFsZWp92udxpg",
	"xmwl5tT5VdobpWK9A5i0KY+NSzZGWulLWIiRzKIIpFxmlBrC+2avNKngdxSSf7xOKnvb3yDPmNlLEn8R",
	"U8LRJgzefl1RHNvSTgHC3uCbQOcvxZ0DlWCv8Mp0QvJHtybfNrUmBqbyM2TnYaf/1dzMzprklHqvn12m",
	"jvtFlABTpW76eFiCs1mrjcZLQ/YcJYnDOfNllKkBKEUrYFoWQJih8bA9Z3N2ZVOarQyPtPP2R9PWyenp",
	"cW/OWuik9e4MRWsscKRlRJSzlX5+rbBw1zsYUf4AIsISEAVdhWt2FJMVUXqku4swLKo2UoYuhsjQ8Nv1",
	"U7oGJvW8EYvt+sWaduicHfxdzJY3mw9iClD9tX3WxphgfOBHHj/91eHA4r36cc+mFoVOvsy2zVzP3yd9",
	"Y+HniXIchyghUmoOkhcWSwI0theyxE0qMWdpJf/h60me14sa81IXQaYSwtTWfPBIpDKXX3mdEnG2pMTS",
	"r28usLroWAS6hsi6CXfwHf/twC7acwUqE+56c135PscV6EUcqEbfD6DOi69rvlDGPvcfPuy0MZHIf4hT",
	"1Zr7cGewhqisM7fiPo1VOvZGYRSarpOH5jnCxTdzB6cuO3Vn6mpSSTGkU/0ksoEyvdnd7rSHaQotb74e",
	"6r0weUPlm/Q7Z9+9fhfu9CrDIA8BB7p7QltXnk3O9sXA0v2amW0ftf4/ALcA+AHUC1HfNYqbKe+uajov",
	"1TsGDm7dHR8+Rjp+Fs1TWVBAH5vDXftSsoToKaJg2xaGGDeulJ9oc7v5XwAAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
