// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fprc9s2s/4rGJ7O1DkldbdzrC9nfEkTNZGTEzvKtJWPByJXEmIQYAFQl6T67+8sQFKiSFtO3zaTD+83",
	"icRlsZdnn13wixfKOJEChNFe/4unwznE1P48C0PQ9heNImaYFJS/UzIBZRhor29UCr4XgQ4VS/C11/dG",
	"Q0LtNBJKMWWzVFH7xveSnZlfPK3nd0k64Sy8u4c1Pimvc339irj35B7WZCoVKZZujMVAfILQQEQWjJKQ",
	"yzQKmGCmaX9OqAb7l0zWJFFywSJQOGss3mX/SEyThIlZfywC8jqdwIgp099ZiaQa1CU1FAecfbzuWzES",
	"ypR98DlV0CdlIfHFy4t3fcKENlSEQGIwNMrWGA2XFOfMUtCGhKk2MmafrXLGqB5Y0Tjh4PVRNQFEnePj",
	"9ik5Ozs7u+hefaYXbf7b5aB9dfPiGJ8NXrjhjUbD8z2zTuxEo5iYeZtN8UROUE3exvcuZBxL8TMDHumq",
	"tt1bMrWvCRMhTyOICBOEck40qAULgeCiRCcQsikLreSo1Js5aMjVTBagNJOCiZlPYGVAaDZhnJm1T6iI",
	"CmsE+TJlN2mMq54SKqAG7gyLoSr4DYtBGxonZDkHQcwciAItUxUCWVJN3OSIHL3/+YJ0u93TZyVVd1qd",
	"k6DVDtrdm3ar3231W63fPN+bShVT4/W9iBoI7M6+p4BGbwVf536/p3TfY1FVvg+C/ZECYREIw6YMlPXk",
	"XTEbe9ZfxAGdhO1OFxVBjQGF6/z/7zT43ApOb4+yH8Htl5Z/0t7kz5/97w9PkTH3SJT0BwVTr+/9V3ML",
	"AM0s+pvXzuTDfPjGCjOvHvB9rm18TaQiXDrXIEtm5syZRK+1gZjMGSiqwvl6/8zNRMkoDXFaM9UBUG2s",
	"UKl5kuJzp7qbswzEHjtaDgGv7OCN72XufefWfZJebnAoTjXUpHXxlCoFwhD3nsjpoyZXqcCAecpR3YJ3",
	"MWhNZzXx8CqNqQhwGTrhCEB2XBZ2TMxIBIYyrgmdyNRYqcKSrCXBCuMyTTIhicDY4Hz9FGnTJPrrocup",
	"NsSt8KT4Pe73jvvdvxy/GxzxR8oURF7/97JT7MTNbQ22XjJ9/5VZkimTUk4ipu/LiFqFP5rQkJmaFInb",
	"kvy1DTeSYubS6XTKVuRoeO6Tl+c+uTkvK63dar0830MXhJCfjobnf748//Pm/NkPXo01Ba0zo5ViB9+O",
	"Ugd5WfiPhs9cjiBKSkMWkqcxkDjVhkyA4JIRGXsTKc3Ya4zFWaFCqxtNQiowFduRmnB2D2Ts2Zzq+WTs",
	"cTnDH2DC/aDCJQ9B6H+X0fNxj7DH97f2qPOEF0pJVdXROyUnHOIi+ACHobcnUmhwzn3aO37+rGJ9N+Ng",
	"nMMq4VQ43C0yq5HEzJkmMnQhHkJJQWiTH/FQP7q8b4M8Oy+ZpMYGoZAmz9lRnU/kVKcm870fEAVTsBtn",
	"WY/prXROBw/I1rRvdbPd6ULv+OR5AP9zOgnanagb0N7xSdDrnJy0e+3nvVartRvvqWJBsan3IH7W6PPm",
	"5l2O1qGMStL0Wq1iJSYMzEDhUoYZXnPu67lUhszL9tFpHFO1zhNB4vyhdOSBWFDOIjIQSWrqRM/T02Nq",
	"zuJwjUCNGzklZxi23WtuTKL7zWYUxo3saSOUca515kQJWCbKU9W7FzDZtk5PddHyEqnw2+uvg047ieAY",
	"avCYGbfYp5F5ltfI9K0u3l47AmvDApgiLMbUGFJDuZzVMc96jb/d33oLfrbEuKIxvgylWOBzKfpknLZa",
	"3TBi2ihpf0PgHmVs2T0bi4zUa1uVvGEiXfWJmgMPTn2STlJh0qDTabR6PplCJBUNuqc+CUEYqQNtFNA4",
	"OMWpH5mI5FL3ydL9CDCbgQo6rU7HLx6227sVUa4oph/Q0F6pdCGFoUxAPkoqguXSyAL8bsEzGhIDccKp",
	"sYNCKQzSDc4mCkOCGYiLGutsOCCDy50Ka2DXLnxunzhZ3TzNEesc8BVQXkdq3fMcDzQTMw5GioKfVDyl",
	"nhtfUCEFCynPyHGZBZZOIu+fzv4OyFtd91B56HurgEISFJK5E2He1Ki/uVPTre8lPFWUI4LYR7hXoZ1c",
	"anyQcqqKUTsSOFKV8/UG4g+TzWwYCjaEWKr11yGCm1NGAHL0/mxYTaeafa6J6GwBfPk4jWqMxZAmNkBc",
	"GR+7mVmdvNtqKDOuk79AuPYJKYpe58TleuZBzT2u0cqq+5iXkbLD9ftYnHEul5pgxGPm2A7VYBA3tVUy",
	"lh8TBfQewTKRylDXJyhhNzI/W9Rh5KyJglDOBJqJioiwmZAKSCruhVwKN84K8BrWmlBVNCXUDkRrcgSN",
	"WcMn9+kEFkwZnyxiBCqf0KVGC48oT6E8/4HTEqeufXN/8ejSKjwnRzdOuabbWHGqZrZyzLevGZe2G8Uw",
	"JxsOWsSrkcsW6FDP67s8+2X7w+V6XtBYZparJ6vcUbkzuQAlUKrGWHzQSAnXT2gGVSKO0wnwR92ygnJl",
	"iV/DOligSWzzTTsmSWczdBsUdMq4AZzaGItzaebk3lpfRGThDJnXGm6DqrFALJiSIgaBFGfbifB8Ty4F",
	"II4VrmyAxl6d4utro0Lb+LrME4aZVOVqCfODrXQSWm0TxOsggkWwQN4Y09UbEDPMOidd34uZyP+2H6h5",
	"guzX19c8tw872k0tQ7redZHyqek9aEeB6ZpLGhENfBq46ZPcpCCQNGuiZIp40bRsdKc/CCKNUTqriTDn",
	"IZ5v68IJ1bZM46k29qGZK4DAMFABTZIggljikXY7bnV0+9pIlbVYnp6KskkHet+2sq2q7eGmgIO1984w",
	"6KiOIVofys5PqCEcKFJjAW6JcnG9bTxu63Bc5DIfuo2Uqk+OhpbZSgN9gnUjLuk2UVuhsIAEMZUqhAjF",
	"oUnCc0jhsADurIeE72CTzrZUNtaxB258u7ARVYquK67qlFrnq6Phw7oe0nDOxFMJXbnZufXsvQbuk+vW",
	"w4QvgfCQqkbDaxxV4Qv48PYQtUNhvyziOxZtSvxuEefcLqNypSCpp3GL2AoxGr5h2tQ0QeiMCdvM4wzd",
	"dEpGQ11RvICVuUvoDO6MvAdR0zbEx9aZFRjFYJHXujiTJLYUmSLJTrkpc2FY/5L8djE4GXx6sR52PrSu",
	"bn7tvvn4off248AMb365H67b86vLD503N/+3vvr06+rq8kX36vJsObz45bQOIRbOjZ/kz6PhTtrYOnCN",
	"r15nJqecv516/d8fX7d0rbPxH8eqsqZpcbv32AbZHeDG9yzjvZMHZ+RVvb1tyNn8YxMyzm/rmwJzH23C",
	"Z8PQBmGSHtQ9jtkPDzuxkHC79c45q1hy61cbe44g0pmQ2rCQLDJgiR2wlHHcwvjA3a5pEpYu3Y52O85+",
	"wc98Ur7deDYWCU81GQ23pDRbYWqra3tr4pPsPO7Wbb9b0igX/kZRoW19bst/OtFG0dCUZd92BQQ1bGFb",
	"ejE1DtOrfpzZ5etb4hfvPhxIn6FMRQ2+XKXxBBQG/2K7lN4p2RZu6RQz1eMFW88mHhYjzWhXe397ruTk",
	"qXrLxvZHp9LJLAwNUeoqwc1aKiSnTcUd9dm7ged7nIUgtA0KxzK9s4SGcyCdBuaQVPGdjt5yuWxQ+7oh",
	"1ayZzdXNN4OLF1fXL4JOo9WYm5jvNDAPCrAoyo5Fm/JkTts4WyYgaMK8vtdttBo9V97OrYGaGTLOwNTl",
	"UJMqoQkt0sBeyCBoZw4rxSDy+h7mkyxXUEVjMKC0Rca9Mp6u0GREFI6QZQGSgLKZAdkHjvwjBRv0mT5j",
	"unIpx9bYfvYJhBN9SlNuvH671bKkO/MJ++9RD3k4bSUuDzrPrhNnJ/vtyrLP1G/RC90NgtV2p9XKPQ1c",
	"fOwQsOYnLcX2847D6crmcOvCeww3tQlhmnJSGAndoffo7lnD+6evk8LdptQIcU4jSzxBZ72KzErfav8P",
	"AlaJ+/4EsjG+l/X4M3+1+OKc1tBZxrW8243vJbKOHV3YDxUIJQKW+xGRXaCNhmTJOEeGboELgxIiIh1F",
	"L6I4q3wcpJUDyW0yGh6KpKLdMxqSwWXeIogTaTu39puKh92XRYfd1pruXEbrv9FjnaG2wIxJZlOJkfbf",
	"vmPl+6f8mxNdhApff/MQya+T3B2O3f302+1+IcWUs9CQwHmtmTtqYfsglGPdsyawYtp9gdHrdL6dbKOi",
	"m0BgFUKSI9j3hiIFIth4LYHIxrc5Nm+cP5Rqs2uBcA7hvQ3iQ5m+jBYvwbzKG/j/WKZ5lff+qz3n13sK",
	"2T3Ojkby24lCK18W8SDaOHVwMHXfLNjnhFbY+lTJ2H0UU7SPyjpxMw8jaPW7r+z2ZzREKpoJlgGobTYU",
	"+InSe/tA9nVEoFfT8Bhmm34nuDS4JDrFbSByMvS+IQIM7XcNU5mK6HuM/MI9q5Hv10f6SzA13jxZE2Z0",
	"3s4bXNZF+L/lyv+YA7f+4Sz9XbDY/4TC4VBwjl2TAbPvNnOXdVVwkyasuS1Sb4tJB9q/2w8PYyrozHaz",
	"d/3Zq9Zzpdxa+JDezsovtW83/woAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
