// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFn/btu6FX4VgrtAE0yylbTrbfXP0KXdTbBuNeJ0A1ZnAS0dW7yVSJak7HiBgT3EnnBPMhxSP205dS7a",
	"/ieLFHl+fd/5SD/QRBZKChDW0PiBmiSDgrnHN0sQdmqZLd3PFEyiubJcChr7QWLcKFlzm5EMWG4zIheE",
	"5TnRsOTGgoaUTCeGBlRpqUBbDm4xxWy2v+gFE1LwhOUEx3EpmwHRYGSpE6ABhXtWqBxoTP3ONKAaWPpB",
	"5BsaW11CQO1G+XHNxZJu3cYrnoJ2+3ILhXv4ScOCxvR349b9ceX7eFJ9Ufm+bRZlWrMN3bYv5PxXSCwN",
	"6H3IQIWNpd5DC1oYGn+qjb0NqMpLzXJcqg0uoBuGi2UOFsPg/cAXZc50fy5tbcGXozQpRlyOuzPQvHda",
	"S70f3+s/X5CfX0U/E3Q650xYAjgTQ6ykMLCXpxQs4/n+SpdlwUSIsWfzHAjcq5wJhoPEKEj4gifESmIz",
	"bohMklJrELsZBL3iCRD0hzxbFc8IN4TluOaG4CCkZL4hdfpwSlj/eEYHEs2FsUz46Pet/Xh9RTQswBlB",
	"FlJ7wxpLfRB6di6kLpilMS01D5tvh7Y1BxByeXMzqQGSyLTn/IvodbMSFxaWoF2ZcZsPmD/NpLYk64fc",
	"lEXB9KYGidJynkPRi/C0ivANRvhCikXOXbHuueBfPB41noKwfLHhYuk29DFzX3b3zKxVJh6PsTCrt6NE",
	"FmM33YyT1opjI7xFjH8puYYUsVTt6EN1u4vEbUAvHQ8N5MPzU5WRBm9devnGHOUZ8RiOOlhDXZsH1t4M",
	"hutp5FRZ2SUn/+prtNS4N8RI1SCaU9PpQGFXBVrPqLqG9kRyMDGJBmbhzvJioGpveAHGskKRdQaixoZf",
	"fs0MWXBtbKc9dSsxZRZCt+wROUu5UTnb3Ak2ZMYOQVaTCU6uCKi1q5fYt8yyOTNAdoMzBFwQqZJc2CHw",
	"vscAaHA7udSQhGFQWZK5d9PJIHCN6uI2fhW9inbAOsi96YAJgn8pG+LgoBvHB1zr9AUVpvMwis5oQAt2",
	"/x7EEnH48nlACy7qn2dBXcQ0pv/6xMJ/R+Hr25PqIbx9iIKXZ9v6/ekffzompcOprPxwqavgvle4J4JZ",
	"BA/5DJvTnjvpPFSPZHCYZK6r0vcc00awt3IjbMbdkH2da7ztd8Ok73qFXJCmO2OjbAAkFwvQhpxIAUSB",
	"JtPJjrNV8Q55Wqr0t6M2Z8YSv8JvRexOH3G57iBoJzC3T6XRNhsP9eMdT7c9Xm2laI9I9+ujR6XNcJdM",
	"p8d0DCfGe1J8H3h9asU43yUZJJ8fy1GFApeUSvb7b7q1cB6dvwyjl2H0h5uzKH4exVH0z0OpOxKJDdzq",
	"5DWbfX5lwkQKy7g4gLM2J8cwVauqBgmq2aoC3RNBNu1K31bq9rDW2/JR1w6JhwunZpsM4TQYckyUBRbw",
	"NQpvGtCPotUWHwVbMZ5jC8NCbg2qJx8pJf+Rgc2gIv8JCn0o5pCmkBKpCdwjiljeMaYedlGoRnsGdCZ8",
	"TQBtt+5wsJBOO2AkE2yY2MJ7Rr69+Ct5J1ZcS1Fg3PwR983kivzvP/9tjCSPixYm0plgncPxiNw0DZgl",
	"1hBmXBhQ9usCUo4ifg52DSAImsBEg9OZqDcxJAWVyw2khAvCiGV6CZZAa+5oJmhAc54AnuPihwpC9I1i",
	"SQbkfIRtvNR5p9Wv1+sRc8MjqZfj6lszfn918e5v03fh+SgaZbbIO0cTOhggGtAVaOPDuDpjucrYGX4l",
	"FQimOI3p81E0ekF9v3O1WivE+IEuYUDAvOcrEGBMj2AaBbFnBnWb+SRcpTSmv4C9bPW3P966jc+jqC4E",
	"8MqJKZXzxH06/tXg7vU9yNduCi5rlbtXTB/+4iqxOqW1xFzzpGXLnvrGyePeVYWSxg4pA0/mhIlHStJd",
	"yDTCbzQT190a5QaprlASA4DSpQCsyo6ECYjX2KHUoe+6p6OZwOZKsPVPJx4SAxh2AwWrTvCEkSXmkXQP",
	"+zOB0sFbRq7q89OXEoyFtDdz+EaACYlkMhPTSdAHHzdEA2IeUh+CF9Hr5uDrAdIvkgvnZbcbMs0KsC4F",
	"n3Zj/8E94MmvjvPVW1eRnWh27aFIOzSmX0rQSJYVIjmSVltf31bj7pLhrVc9YOyfZLr5ZoU/aTVJT1eh",
	"8tp+R8D19z2gDiqdSE40hL36GJMc8GilQcCa5adIUefR2Y+1ziMrJScC1r1ycea8eDRY1S3P759mlr8N",
	"HLDpSqxYzrGlqNL63V//uN1rYDrK6MH+IOYb5M2EM/f8/MeZ+3cMla8juE/Av3azFqzM7Y8z5KOAe+VJ",
	"Dqo53UZzVIfodKBGCvoe1KrJwbZ8DbbUwkuYXWG5e++/s6eZiZO5tFnbN1Dq1CaeDvHzL9Dee383TnnT",
	"uzzfC/f+Px0N/VcBQG2JhxpXEL1cdL/thLz+P8Dt5oq86jden42Z4uNWRt02Hz7t/qwJpWl7T3uWDB79",
	"R2foW1P/HXLgzOkV2tCX9WXg7fb/AQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
