// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fr/ctu4EX4VDJqZ2D1Soh1fLlH/uEmUXOJpcvHYTjvT2PWsyJWEOxJgAFC24mqmD9En7JN0FuBPifKP",
	"9M69ztx/MgECi8W333679DWPVZYridIaPrrmJp5jBu7na62Vph8JmliL3Aol+Ygf/zBm3z2LvmP0YipA",
	"WoY0k2k0uZIGecBzrXLUVqDx71sQ6eZKb4sMZKgREpikyPAqT0ECDTKTYyymImZWMTsXhqk4LrRGGdPy",
	"eAVZniIfcYN6IWJkdpkje7zIHjNhGKS05pLRICZssmS5VguRoKYpYfXHYx5weo+WsVrIGV8FXEhjgXbZ",
	"sPbj8SHTOEVnBJsq7Q2rLfVO6Ng5VToDy0e80CKs3+3b1liwhelx0enpEfODLFZJ5/AH0fN6JSEtzlDT",
	"UlbYtMf8k7nSls27LjdFloFeMjVldo7kpkmKWcfDJ6WHT8nDYyWnqYht3xH8g5u9JhKUVkyXQs7cht5n",
	"7s32nuMPP/7w7nB8eg8XrgKu8XMhNCZ89ImXS3pfnNez1eQnjC1Z+xYhtfMeh7vnlcuNkLMUrZIEblXo",
	"eBPcOfQtMwappIghZTRe+be1SHPYubeE7Ifkg0yXfGR1gfcBSdvmnrWXve7quiTgVyFgHtYm+qNZ1NKQ",
	"Q0srzwOep4WGtF6cNqzdVJlOD4oUdPt45X4wQ2kHSZwNhBqWg2TOURmVPcgtEVjNYBpnwljtmWLrxcQa",
	"weKFFVkPLE9FhsZClrPLOcoK/H75SzBsKrSx5UZImGohMQGLoVv2DneWCJOnsLyQ0GfGGgOWkxlNLhmm",
	"satzsa/AwgQMsnXn9EUmyiRXQtq+6HxHDtDodnJXw2Igp0I8d89OjrqAsjY3o+HQ5IPy4SBW2ehZ9Cxa",
	"C9Zeck16TJDic1Ezg0BdH7znaC3iz8NkEkbRHg94BlfvUM4oDp8+CXgmZPXnXlCBmI/43z9B+CUKn5/v",
	"lD/C8+soeLq3qp7vfv/oLleagrEX8Rzjn2/CVRnyNJl5mDP/TvsU+9H+0zB6Gkbfnu5FoyfRKIr+9tVQ",
	"y9BCAhbIqkcap3zE/zBssvuwTO3Dyp/vq/mrgPfDs7wbB8fyPBvBuCPBEiGwn3G52zlcMgnzG1BJsepC",
	"uIfR3gljacdmDjNFnittMWml3lbyb+/8qYx9HvAEU3Q/ipx8SfwlLGZuyy0ZjIPWsKS/+6n9uCQcz+wN",
	"bjtnrw5uhm2g3s7w7oouFqiN22yDCt04K8erO+mIIB+0lbu66WCxB2k+BzKlFRaLTwT+b3bc2D8maGH3",
	"e/foj496pYrf7aI/3zuZoKaNTXRRNbWq6RS1YTtKIstRs5OjNciUtHYfiTR2eqsOMpqGLUFTU4csMoLG",
	"MUlDHvCPskmOHyUsQKTEwYSQxp5q8q0X1++Mv87RzlFXdyIMw2yCSYIJU5rhFd0ApC3jqmHnlHK0Y1Dr",
	"nVtt8pD/ygToeMuv8LXJb02SOYppJaM1JG2A//y+EqWJuevq54VIVh3NUs/hHZGyyVMdmVIPt4XK+xbd",
	"QpIIciykRy0N4r3S9fuLeiar+JrBRBV2Ha9dMUNKRMkLVwJs3OUbVDMN+VzEzM9zpUIrsTfx5/gUu6xQ",
	"mBDB2HCvL+oqZ5vbskpFi2PIIRZ2eZeQrekd0kpx9wTu7Wo24F+U7HHMCx/VIhV2yWgKhR25PEZpUW8j",
	"72ZGOLmDdF4FfOPw27NGXE5hQvqgovH167bKQnoR50VP4NIQGx99ZLHSaFjDXF1hEfXWaG7dDDOll9uW",
	"9qNb1t07fbl9XdmLTr+qLLKJSwCMZnUAuBdFvXWsW9NYpWG2ddlyeJsX+qzdvL+Vq/unylUNSlqISSqv",
	"1kP31fg9ey0XQiuZEXpfOLn84uiQ/fuf/6rZnN1croBMzmQGEmZIiwzYaS28IbaGgXH4Jz/oDBNB1fkE",
	"7SWiZGQAyKTa4UxWWxiWYJ6qJSZMSAbMgp6hZdgYOzgjkKUiRmmcM73g4y9yiOfI9gcEl0KnLYl/eXk5",
	"ADc8UHo2LN81w3eH49c/nrwO9wfRYG6ztNVz4L3u4QGvBU0jQbwClJALPuJPBtHgwKuSuQuAqjIcXfMZ",
	"2j6BuECJxnSkdV05bJjBW3LzMHGUad82dbfvW7mNKXBKGKCvmCDPUxG7V4c/Ga/KPOndRolvq+p2A0of",
	"/kznP7hxr7IZ88399vRNu54tX0LCKB2jsX7vvYfb+6OEws6VFl8wccGi0ffm/sRogEjYb8wSnKLWmDCr",
	"2LSwhcZK7LrALftVTc+jKqkszDptCpo8bJL9Nhgdoy20NAzStFXsb4SwYTsTZeeNeqMorAJ+90wKGadF",
	"Uja1hGbxpiQtjA/BLgypzjlqSZL/CorrisEUqe/p1hXPXarCzUKonzD7C7aWExvv/w71+0I94N9GTx7O",
	"6ArvRasO6oabu1+Kko3QaAVfLdrOqXhWpjfgPD4YyBsy5qWw86YjNTiTx+0UKgwJtyxX5Bm247oTYFir",
	"DxEw3wAIlQ59DbM7OJNUqjASgSdHPmP31GJuIIPy2wEDNqNE06mwzyRVrt4ydlg1dh3aMOnW4r3fIkAq",
	"KgrP5MlR0NUGwjCNFGGYeBccRM/rlnsffYzdKVv9sRw0ZGgd5X1a9/2HvJTadTlw+MqlzJY32/ZwUkV8",
	"xD8XqEl0l5JBJHWtRvf7yzbf1rXaua8h0diXKln+Ypm5IbtulUoV2+pXVATdfbvXU6O/rLrZjsawg48h",
	"SxEMoU3iJaS7xBP7N5Lbr2Cdj6yE7Ui87MBl98F5/lAuIBWkefPi/5fpD6LnD2d0xSbO4A5XbSWqmi7O",
	"vLn7+w9n7l/ofr0T8SpG//i3lx3vlNX6E2VHp641rm5VreX3yZukK13k4auANRJVWHMm76xQ36C9a37Z",
	"/JKz2cxxCcX11et80joyX+fiB040/0vWn6pCJr9L5a8i0IOHM7q+L6lsc2e/MT56g5bBXQmo/KRTxbRv",
	"Ag0hF8OmV3Nev3q/j/NUJzfNrtbnvM3w56tgy/81+N5O37vVvw+cr/4TAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
