// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fr9btvIEX+VxfaA2D1Koh1fLlH/OCROLjGaXATbaYHGrjEiR9JeyF1mdylbcQX0IfqEfZJidvkpUv5I",
	"79wrcP+J3I+ZnZ35zW+GuuaRSjMlUVrDx9fcRAtMwf18pbXS9CNGE2mRWaEkH/PjHw/Z90/D7xktTARI",
	"y5BmMo0mU9IgD3imVYbaCjR+vQWRdHd6k6cgBxohhmmCDK+yBCTQIDMZRmImImYVswthmIqiXGuUEW2P",
	"V5BmCfIxN6iXIkJmVxmyR8v0EROGQUJ7rhgNYsymK5ZptRQxapoyKB8e8YDTOtrGaiHnfB1wIY0FktLR",
	"9sPxEdM4Q6cEmyntFas09UZo6TlTOgXLxzzXYlCt7RNrLNjc9Jjo9HTC/CCLVNw6/EH4rNpJSItz1LSV",
	"FTbpUf9kobRli7bJTZ6moFdMzZhdIJlpmmDasvBJYeFTsvChkrNERLbvCP7FzVYTMUorZish506gt5lb",
	"2ZR5+P6nH98eHZ7ew4TrgGv8nAuNMR9/5MWW3hbn1Ww1/RkjS9q+QUjsosfg7n1pciPkPEGrJDm3ynXU",
	"de4M+rY5BKmkiCBhNF7at7FJfdiF14T0h/i9TFZ8bHWO93GSps49e696zdU2ScCvBoDZoFLRH82iloYM",
	"Wmh5HvAsyTUk1eYksDJTqTq9yBPQzeMV8mCO0g7jKB0KNSoGSZ1JEZU9nlt4YDmDaZwLY7VHiq0XE2kE",
	"ixdWpD1ueSpSNBbSjF0uUJbO77e/BMNmQhtbCELyqYYnxmBx4La9w53FwmQJrC4k9KmxgYDFZEaTC4Sp",
	"9Wpd7EuwMAWDbNM4fZGJMs6UkLYvOt+SATQ6Se5qWARkVIgW7t3JpO1Q1mZmPBqZbFi8HEYqHT8Nn4Yb",
	"wdoLrnGPClJ8zitkEKirg/ccrQH82SCeDsJwjwc8hau3KOcUh08eBzwVsnzcC0on5mP+948w+BIOnp3v",
	"FD8G59dh8GRvXb7f/eGbu1xpAsZeRAuMPt3qXEXc0wrmfZ25ha2j7If7Twbhk0H43eleOH4cjsPwb1/t",
	"bylaiMECafWNxhkf8z+M6hQ/KvL7qDTqu3L+OuD9PlpckPPJ4jydiNyRYAkV2Cdc7bYOF08H2Q2uSQHr",
	"4rgH1t4KY0liPYeZPMuUthg38m+DATQlfywAgAc8xgTdjzwjWxKICYupE7kljXHQGlb03I/vxwXqeHiv",
	"nbd19vLgZtT01tth3l3RxRK1ccI6eOjGWTFe3kmLCfnILc3VzgnLPUiyBZAqjdhYfqQI+HbHjf1jihZ2",
	"f3Cv/vhNL1/x0i76k77jCmpW60QXVeGrms1QG7ajJLIMNTuZbLhMgW334UmHjnRVQUbTsMFqKvyQeUqu",
	"cUz8kAf8g6wz5AcJSxAJATF5SK1POfnWi+s3xl8XaBeoyzsRhmE6xTjGmCnN8IpuAJKGcuWwM0ox2lKo",
	"seZWnbzLf2UWdLjld/jaDLjByxzENDLShid1nP/8vjyljrnr8ueFiNct4lLN4S2m0sWpFlephptshTCq",
	"a9cJzIUko7GkwLCmyDZNkXhlLzKY44VVn7An3E/ptcM7jVYLXJbkmVYyWkkCNJo8cZHecYFyaHxdw95d",
	"UkMXDdc9RLqTSMbXHOJYkPaQTBpn9f7RPtzzaiYrMxeDqcrtZuS2jUbETMkLVxF1DPYa1VxDthAR8/Nc",
	"5dTgOTUSucyCbXzMzQDB2MHeFls6t7vViGWCOIQMImFXdwGvKtFBUhYgPRB2O7kP+Bclewzz3OObSIRd",
	"MZpCAEQmj1Ba1NvSWD1jML1DJbEOeOfw2/NnVExhQnp4ofHN67bKQnIRZXlfdFhI2OHkA4uURsNqDG9T",
	"rLC3ZHX7ppgqvdq2tR/dsu/e6Yvt+8pe7/S7yjydulTIaFbLAffCsLesd3saqzTMt25bDG+zQp+23ftb",
	"uzbITLkiSkkLEUHcejN0Xx6+Y6/kUmglU/Le5656eD45Yv/+57+qvMZurt5AxmcyBQlzpE2G7LSqQyCy",
	"hoFx/k920CnGAvSKTdFeIkpGCoCMSwlnshRhWIxZolYYMyEZMAt6jpZhrezwjJwsERFK44zpqS9/nkG0",
	"QLY/JHfJddKoeC4vL4fghodKz0fFWjN6e3T46qeTV4P9YThc2DRptGB4r3l4wCtqV5Mxz4UlZIKP+eNh",
	"ODzw/GzhAqAslMfXfI62jyovUaIxrSKjKqQ6avAG8T6KHWTaN3UbwrfxnGAKnMIN0BeQkGWJiNzS0c/G",
	"81MPerdB4puy2O+40vs/0/kPbpRV9Ka+vZ9M38PsEfkCYkbEBI31svceTvYHCbldKC2+YOyCRaNvVf6J",
	"0QCBsBfMYpyh1hgzq9gst7nGkva7wC3ad3ULqCwuLcxbXRuaPKo5yDY3Okaba2kYJEmj99EJYcN2psou",
	"ah5LUVgG/O6ZFDJK8rigKUKzqEvOc+NDsO2GxKYmTaYEGlK0TuWPm8q+gyuR5mkDSgui44oK4kWccIyP",
	"+eccNaXJIshTuPKEy4gvNeX01phBntgCg1MvoHwSsnjqovM6+K9I2/BMvp9aEJLqWq3SamKDF7KZwCSm",
	"RcAyjUuhclN13L0t+87aIJbNg27mgPNfMexbVLknGsoyv+Fwtaf+Dgv3hYWAfxc+fjilS2zIG9VzG5rc",
	"/RKidGCkAVQVwT1fBzxTphecvH8wkDewi0thF3Uzc3gmj5t0QxgiuWmmyDJsx/W0wLBG9ypgvm00UHrg",
	"K99dCk+ZrBgR5pOJZzc9FbwbSKH47MSAzSkpt/oyZ5KgyWvGjspvAs7bMG53cHo/Y4FUdoH6TJ5MgjaP",
	"EgQGRN8w9iY4CJ9VX2v6oPbQnbLRWr0Ra99nRVlSlU5HLx26NazZ1GcLGom4hUK/bN+2F9OcbV+oePWL",
	"w5kPhrq3QdXt+gFgtC8IK+8vejVsR+Og5R8jliAY8jaJl5DsEk7s3whuv4J2PrJitiPxsuUuuw+O80dy",
	"CYmg+iDL/3+R/iB89nBKl2jiFG5h1VagquDizKu7v/9w6v6F7tcbEa8i9K9/e9nxTlmtP1G2OP1Gu/NW",
	"hl982r6J5tNFHr0MWE3nhTVn8s5s/jXau+aX7kfAbuPLJRT3NaZmt/WR+SYWP3Ci+V+i/kzlMv6dKn8V",
	"gB48nNLVfUll6zv7jeHRa7QM7gpAxYfAMqZ9w2wEmRjVfa3zaun9/tcBMmZ1Y7DxEbgb/rxbfzf7Ib1r",
	"y3+enK//EwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
