// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package v1alpha1

import (
	"time"
)

// Defines values for ProviderStatus.
const (
	Ready       ProviderStatus = "Ready"
	Unavailable ProviderStatus = "Unavailable"
	Unhealthy   ProviderStatus = "Unhealthy"
)

// Valid indicates whether the value is a known member of the ProviderStatus enum.
func (e ProviderStatus) Valid() bool {
	switch e {
	case Ready:
		return true
	case Unavailable:
		return true
	case Unhealthy:
		return true
	default:
		return false
	}
}

// Defines values for ProviderType.
const (
	Embedded ProviderType = "embedded"
	External ProviderType = "external"
)

// Valid indicates whether the value is a known member of the ProviderType enum.
func (e ProviderType) Valid() bool {
	switch e {
	case Embedded:
		return true
	case External:
		return true
	default:
		return false
	}
}

// Error RFC 7807 compliant error response
type Error struct {
	// Detail Human-readable explanation specific to this occurrence
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference for this specific error occurrence
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int `json:"status,omitempty"`

	// Title Short human-readable summary of the problem
	Title string `json:"title"`

	// Type URI reference identifying the error type
	Type string `json:"type"`
}

// Health Health status singleton resource
type Health struct {
	// Path Canonical path of the resource
	Path *string `json:"path,omitempty"`

	// Status Health status
	Status *string `json:"status,omitempty"`
}

// Provider Service Provider registration resource
type Provider struct {
	// CreateTime Timestamp when the provider was first registered
	CreateTime *time.Time `json:"create_time,omitempty"`

	// DisplayName Human-readable display name for the provider
	DisplayName *string `json:"display_name,omitempty"`

	// Endpoint URL where the agent can reach the SP
	Endpoint string `json:"endpoint"`

	// Id Unique identifier for the Service Provider
	Id *string `json:"id,omitempty"`

	// LastCheck Timestamp of the last health check
	LastCheck *time.Time `json:"last_check,omitempty"`

	// Name Unique name of the Service Provider (natural key)
	Name string `json:"name"`

	// Path Resource path identifier
	Path *string `json:"path,omitempty"`

	// ServiceType Type of service this provider offers (one per SP)
	ServiceType string `json:"service_type"`

	// Status Current health state of the provider
	Status *ProviderStatus `json:"status,omitempty"`

	// Type Whether the SP is embedded or external
	Type *ProviderType `json:"type,omitempty"`

	// UpdateTime Timestamp when the provider was last updated
	UpdateTime *time.Time `json:"update_time,omitempty"`
}

// ProviderStatus Current health state of the provider
type ProviderStatus string

// ProviderType Whether the SP is embedded or external
type ProviderType string

// CreateProviderParams defines parameters for CreateProvider.
type CreateProviderParams struct {
	// Id Optional provider ID for idempotent registration
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// CreateProviderJSONRequestBody defines body for CreateProvider for application/json ContentType.
type CreateProviderJSONRequestBody = Provider
