// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fpdcxo51v4rKr1z4bzTfNjJzNawF1MEE4caG1MGe3Yr9rpE9wE0UUsdSW2bifnvW/pqGrrBZGqSysXe",
	"GbV0dHQ+nvPoyJ9xLNJMcOBa4c5nnBFJUtAg7a8bwfIUBsmI6IX5nYCKJc00FRx38GnvAlGuNOExoMEp",
	"OkritBEGGjRBjEyBvcIRhieSZgxwB5MsayREk8aDFY0jTI2ozGwQYU5SM8l9u6cJjrCETzmVkOCOljlE",
	"WMULSIlTVWuQZvV/PpDGn+3GL3dH/o/G3ed29PPxKoy/+vUHHGG9zIx0pSXlc7xarYI0e9a+lEJWD3n1",
	"rod+efPTP5CxE6OEawRmJpKgMsGVOUImRQZSU1BuvSaUVSW9z1PCGxJIQqYMEDxljHBiPiKVQUxnNEZa",
	"IL2gCok4zqUEHkNVb2MyZ+PqHtecfsoB0QS4pjMKEs2EdCKd1huCZ0KmROMOziVtSJjBzh2VJjpXNWea",
	"TEbIfUSxSDaEUq5fn6yFUa5hDtJI01SzGuXHCyE1WmyaSeVpSuSyTik3sC3F+hGZb0Ej4HmKOx/wYHjT",
	"PR+c3nevzq4v+sMJjvDwcnL/7vJ6eIoj3D2/6ndP/33f/9dgPBnjCI/6VxeD8XhwObw/7Q8HfTPpeti9",
	"nrzvDyeDXndiRwbDSf9q2D13H2+6g/Pu2/M+jvC77uC8f3o/uur3Loeng8ngcojvDjf6qhz7H9zXYLq7",
	"YraY/gGxNtZ4D4TVZakbD05SlM8ZaMFN/IpcxtX4zWqTvUe44DQmDJnvSMyQXkBZyDrHF04Toz9JLjlb",
	"htw9PKzKOtfI/oJwuPIauohYJ8aGVKWFJHNoKJAPNIZGJsUDTUA2kzhtUtEqTrTTeS8eNc80TeuCHmLB",
	"E+sYo+QCkFcCBSWMGaSGpKzx65/b7Z2bljLtAaSy+1S33dpkmlOWoDC/bJzjZrvZfvmI9fFauNAj/HoD",
	"b5BKKEf4qUEgaxShtYZ6ZQR7X9xFOGO5JKwICrNLEd5FuaB8njMiy2FZKH6Q083BfsunIDloUCM/6T31",
	"BZMkCTU2JWxUyqIZYQqiLZuvpTQKwB/d9JACrSmfK6TyLGMUEpTzBOQtDxrdL8xuzY/F+uYtv+U9ogkT",
	"c0SSlHKqtCRaSGXi3KQpWxq5JqAUIKIQF7wBCdUWVBOYkZxpI6eS/iSOQan71GBn5zP+QcIMd/D/tdY8",
	"oeWrZsvRg65dcGHm25S2Vr2PGVE1mT12n3vmKzLlHh2JB5CSJqDQeBQ02yQN8+x1I1a0Luk9VThcW6fn",
	"qgZAD3Sti6vNU4Wla79aj6GZFKnN6dj5qmLstUtf0n5XCNYexVt5nEG80wUF6XAUxPCEWAIxkYgIcnZF",
	"R9S4IDWa2HNkQroIUkGIxxGjwqvK8WKSkZjqZR0sf8pBaUgKSWEuOoLmvBmhW3zcbp/RW7wZC3bQ4UnB",
	"/gzF+/Ho9rbp/nr161GfPo/o84Q+n9HnC/r8G33uP4+eJ89nzxfPv9WywQinoImhpgfGUZi9socu5elL",
	"67f8F2Fvw/v6AjYuWbhM7I7SXGk0BXQbcs6byrMdP1gC2B1IvbF9yQzR2n13e2JsRwnvWZqpA+/wfCE4",
	"u7g2HPWYyJP+g42wjCyZIAnKFShPWnmelg81urq8GRhGNhie4QhfXQ/9X45s4Qif9s/7Ezdm/+yf1lgg",
	"8jebqtpuvOA1SEImQRmj27TY1r8a8SaF4L6+1k9oCkqTNEOPC+DWID7PHoly2WfLfMEyEqKhYWUdwDBo",
	"8rWuaCl5Ogc+N7Tw59cRTikPP4+jL7+GvXiQegJaEDnLP3cQOaeyalXP8DIX9WC5L3XLuLpBXwljlzPc",
	"+XDYcrdsdbetlaWJyV+NH0aURm79Xw2ibWQw5/xighZ88Lm4xq822Jr/jjfIWeGnA8mZn78qUrnEQip2",
	"MyTL0RpkiMIWz0L7adYVkOR3STVcmhyiBcGyFXPKRPwxoMI/UTH3gvClmXDL1YJISNCMMlBLpSFFZQoE",
	"ypU71INs8W4coeG78SvHygLkbexvMM+70GzhfxZbGjuvk2F75Q4QPKdK19iMzCk3oYQYVdrgtw+1gB6q",
	"gn0cnvR9ZsifFh+h5tIxMcPWbhK0pPBgQNVEsVmJzEqzjwRluOlutmc3oxpSdVipXl8OMZGSLOs501ZZ",
	"340/oUDagwQcciyqYhILr3vI5OfqGbfLqNIiRR9h2XggLDfoR6VyXR0yn9uqxG14abASak7mumovloZu",
	"f9Q4Pjl59ZcAv+H/+v+9LTeni8pIXe9qxIg2oIWKOQbmJOyukwf0Fw65jKB4fRuZipwnrg0XNj1kIw91",
	"9ZZ+a2VOSfwReBJOYnezME4eCGWGVH8xPtvt7nbH8k4w9Dp8ERiWIOldAWY4wm8NBG4Cz8b3mq4r5TNh",
	"yZLgmsQWfHzn1wTlSIpwjq0M7I8nqDsa2OhPCSc2/DOQiirtuKbzp4cJJDiawoKwmYGV095F85ZPDKt0",
	"MhgTjwp1+7aByRMiE5dXseBOYLxEJJZCKbM23HT8nZnRGLiCkurdjMQLQCe2V5JL25fQOlOdVuvx8bFJ",
	"7OemkPOWX6ta54NefzjuN06a7eZCp6zUGy1iM9D/cGswypf6KKE9s4qwyICTjOIOft1sN9/4nosN+xbJ",
	"aOvhmLBsQY5bJRSdQw30m4KACGNb9lwjP3qkemHwmob+dZ6ZmyG2Skg7Nki8pJui3JffFj5sb3pBnmia",
	"p4jn6RSkrwMWcJVxsa0O4bXgUw62I+wtn5InV3YU/dP2nIonAt9NwJ2f2jWN6dRtiTvH7Xbbopz/We2k",
	"raLdtWxPAavTtlQgy6pup4klh+6FwXrqpN0OKQPcOo2YvHV1p/WHck2+tbyXy6Kt+zYf665AKtRoc0XP",
	"LXma5YwtTaS92atLJsWUQfrjl+nknl9q1BnwB8JogqTrGKBSFK0i/NO3VcUUPsIsFoB0TyoWlcMrhU+e",
	"dcxrMrekOIzcmfuNqCNcPVvWEEEcHndlXiXB3KKbUKf2Zthl5vgHihkFrkOvChK0RQWa6HdTl3wlSCJE",
	"Nbq4Hk9ueUp0vLCNo2ZgQU0T1n6FSKnWZoFJiTK3MKyZ2HyRIr3lVQFr9uHJ70sPhltJZZ8K1979ey+s",
	"talpg/GtSJZ/c1a6uNt89VxVsOD4q+xa2wrxdOt7AwHbKXJ6/PLt9PA2sfXP9rNIuhnphBkKt0TwRJXr",
	"7r05Ofl2+tW0VS23TQQoxIV2en2XwOnxr8CyKnKuonoiE15qdvGZK9C55K6Bvdh4DQ1dScexKuh6Bvr9",
	"+i3zKxXj9+GZqWK1QP2oQuHZc9Nk/pm0t4D4Y8liXuIeg5VbM9ZcDHTdFdGOI7L+/4SX6pFbsase1Zlh",
	"PaW18d8mNQTozc52rTtAHUa9+ebYYLJsZm5832WWeZfuybJoZxJZNrgnGtB0uU0l6lLqK0VH+9uVxH3M",
	"+H8BtxlwZ6D3Yrp//6qnrLsuwcUNu2UjwYvd8V8ksYFHVIShWrPGAL3RDlhhdAbxMmbgug32HbRWUDjP",
	"6m713wAAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
