// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FlNc9s40v4rKLxzcN6hPux4shVdphSbsVVjyypL9u5W7FVBZEvCBAQYALStsfTftwAQFCVSspOapHLY",
	"mwQSjUZ/PE938xlHIkkFB64V7jzjlEiSgAZp/90KliXQiwdEz83/GFQkaaqp4LiDT08uEeVKEx4B6p2i",
	"gzhKGn6hQWPEyATYGxxgeCJJygB3MEnTRkw0aTxY0TjA1IhKzQEB5iQxL7lnYxrjAEv4klEJMe5omUGA",
	"VTSHhDhVtQZpdv/nE2n81W68vz/IfzTun9vBu8OVX3/z+y84wHqRGulKS8pneLVaeWn2rqGUQlYvef3x",
	"BL0//u0fyNiJUcI1AvMmkqBSwZW5QipFClJTUG6/JpRVJZ1nCeENCSQmEwYInlJGODEPkUoholMaIS2Q",
	"nlOFRBRlUgKPoKq3MZmzcfWMG06/ZIBoDFzTKQWJpkI6kU7rDcFTIROicQdnkjYkTGHniUoTnamaO41G",
	"A+QeokjEG0Ip12+P1sIo1zADaaRpqlmN8sO5kBrNN82ksiQhclGnlFvYlmL9iMwzrxHwLMGdT7jXv+1e",
	"9E7H3euzm8uwP8IB7l+Nxh+vbvqnOMDdi+uwe/rvcfiv3nA0xAEehNeXveGwd9Ufn4b9Xmheuul3b0bn",
	"YX/UO+mO7EqvPwqv+90L9/C227vofrgIcYA/dnsX4el4cB2eXPVPe6PeVR/fv97oq3Lsf3JPvenui7fF",
	"5E+ItLHGORBWl6Vu3TtJUT5joAU38SsyGVXjN61N9hPCBacRYcg8R2KK9BzKQtY5PneaGP1JfMXZwufu",
	"68OqrHON7K8Ih+tcQxcR68TYkKq0kGQGDQXygUbQSKV4oDHIZhwlTSpaxY12Ou/Fq2appkld0EMkeGwd",
	"Y5ScA8qVQF4JYwapIS5r/PZdu73z0FKmPYBU9pzqsVuHTDLKYuTfLxvnsNlutl++Yn28Fi7MEX59QG6Q",
	"SigH+KlBIG0UobWGemUE5764D3DKMklYERTmlCK8C7qgfJYxIsthWSj+Kqebiw3yR+c0p0kSx9RYkrBB",
	"KXfckZuG9lsbBcbPjRA0lSKx7o6IJkzMcE1KD52GwxSiGg+6hwV3OCYxcB9JIJryGSLIMSk6oMaXiSF5",
	"e2YqpHbo6oXk4WBUeFNBhIikJKJ6UZddXzJQGuJCkn8XHUBz1gzQHT5st8/oHd6sA+yiC4uCxA1T/3pw",
	"d9d0v978fhDS5YAuR3R5RpeXdPkHXYbLwXK0PFteLv+oJfUAJ6CJqTCMsr9ImOIO/r/Wushp5ZTfcrXN",
	"pX97ZS9tXTWeezfv278ZEwbMnA3H9Tg0LFm4zM8HSaY0mgC68wGZmyonrXyxlCc7Em7j+JIZgrX77vfE",
	"2A4kPrHVgvb0kcO+d3ZR/R2cMJHF4YONsJQsmCAxyhSovPbgWVK+1OD66rZniLXXP8MBvr7p578cZ+IA",
	"n4YX4cit2Z/haY0FgrxArart1gt6QhJSCcoY3abFtv7ViDcpBON6yB7RBJQmSYoe58CtQfI8eyTKZZ9F",
	"64IsYqKhYWW9giho/L0q7YQ8XQCfGXZ/9zbACeX+72Hw9dX0ixepryMKPrZlxA4+diqrVvUOL5cUOVju",
	"S90yrm5UIYSxqynufHrddrdtdb+tlWX7+FvjhxGlkdv/rUG0jQzmnl/Ns94Hz0U3ttog3fw53uDYwk+v",
	"5Nj8/VWRyhdU6arFBmRGuTEIYlRpg0K5wXwOqEoGc3jS45TMYKzFZ6ipgEZm2fKlBC0pPBhoML4wO5HZ",
	"ac6RoDKmVR3ReAN0njHVkKjXEc66UsVESrKwd6+g8hY57c4iD/P2Ij6bXC1QMYkFiT3ly3P1jttkoLRI",
	"0GdYNB4Iy0wOU6lci0lmM4utPEZTyjRYCTU3cy3+iwDXDQeNw6OjN98EW4381//v7f+dLioldY30gBFt",
	"Ug8V75hklbAb7V/R7NhcGEeMKLW7nrOP7bFoIjIeu5mAP/Q1B+UJW2/pD1bmhESfgcf+JvY0C0bkgVBm",
	"SsOvRhl7XLXCWNl5xVRYVhVck8jmdz7pMX4fSOGDYyvIw+EIdQc9G2AJ4cRGWGo6CKVdUeJMlmciEhxN",
	"YE7Y1GTu6cll846PTPnhZDAmHhXqhnZgwWMiYxe6keBOYLRAJJJCKbPXl8SqeWcyidEIuIKS6t2URHNA",
	"R7Y3yqTtQ7ROVafVenx8bBL7uCnkrJXvVa2L3knYH4aNo2a7OdcJK81CCvf7OtGXl0b5Ut/k27FVgEUK",
	"nKQUd/DbZrt5nPdYNrJaJKWth0PC0jk5bJWAagY16GowFxHGtuy5Blf0SPXcQCL186osNS0EtkpIu9aL",
	"c0m3BS+UZ4mftg+9JE80yRLEs2QCModai2nKuNgCsJ8OfsnAToByyyfkySG7on/ZHrMYCcYwJRnTuPNb",
	"u2YQlbgjceewbbrnhPL8b7VzXgW76WIPR9RpW+KgsqrbyWSrCDdRtJ46ard9ygC3TiNpynJob/2pXFO/",
	"lvcy81hqtflYVysrT4Oml8uiCJSaZowtTKQd79UllWLCIPn163Ry49YadXr8gTAaI+laS1SKolWAf/ux",
	"qhhuIcxiAUg3QrXA56eSefKsY16Tma2e/Mq9KYRFXU1zYpkDEcThcVfmVRLMbbr1VLA3w65SR/EoYhS4",
	"9gMIiNEW2zbRPw3057VZHCCq0eXNcHTHE6KjuZ0wNH2h0TRhne8QCdXabDApUaZvqpAmNl+kSO54VcCa",
	"4B28vviBYCup7KeBtXf/3s6mNjVtMH4Q8eJvzkoXd5tfOVYVLDj8LqfW9sx5RfOzgYAdKTg93v84PXKb",
	"WP6zgw+SbEY6YaZKWiB4osqNgY6Pjn6cfjXzN1s+xgIU4kI7vX5K4Mzxr8CyKnKugvpCxk9md9Uz16Az",
	"yd2kc77x9cOPr1yNVUHXM9Dn628X34mMz/1YuWI1X/pRhfxnjk2T5Z9FTuYQfS5ZLJe4x2DlHt6ai4Gu",
	"68LsOiLr75Ev8ZHbsYuP6sywfqW18XW5pgA63jnXcxeow6jjH44NJsumpqn6KbMsd+meLAt2JpGtBvdE",
	"A5ostkuJupT6TtHR/nGUuK8y/l/AbQbcGei9mJ5/KKkvWXc1wUWH3bKRkIvd8dU4MvCIijBU66rRQ2+w",
	"A1YYnUK0iBi4aYP9YFYryN9ndb/6bwAAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
