// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"time"
)

// Defines values for ErrorType.
const (
	ALREADYEXISTS      ErrorType = "ALREADY_EXISTS"
	FAILEDPRECONDITION ErrorType = "FAILED_PRECONDITION"
	INTERNAL           ErrorType = "INTERNAL"
	INVALIDARGUMENT    ErrorType = "INVALID_ARGUMENT"
	NOTFOUND           ErrorType = "NOT_FOUND"
	PERMISSIONDENIED   ErrorType = "PERMISSION_DENIED"
	UNAUTHENTICATED    ErrorType = "UNAUTHENTICATED"
	UNAVAILABLE        ErrorType = "UNAVAILABLE"
)

// Valid indicates whether the value is a known member of the ErrorType enum.
func (e ErrorType) Valid() bool {
	switch e {
	case ALREADYEXISTS:
		return true
	case FAILEDPRECONDITION:
		return true
	case INTERNAL:
		return true
	case INVALIDARGUMENT:
		return true
	case NOTFOUND:
		return true
	case PERMISSIONDENIED:
		return true
	case UNAUTHENTICATED:
		return true
	case UNAVAILABLE:
		return true
	default:
		return false
	}
}

// Defines values for StorageSpecServiceType.
const (
	Storage StorageSpecServiceType = "storage"
)

// Valid indicates whether the value is a known member of the StorageSpecServiceType enum.
func (e StorageSpecServiceType) Valid() bool {
	switch e {
	case Storage:
		return true
	default:
		return false
	}
}

// Defines values for StorageStatus.
const (
	DELETED      StorageStatus = "DELETED"
	DELETING     StorageStatus = "DELETING"
	FAILED       StorageStatus = "FAILED"
	PROVISIONING StorageStatus = "PROVISIONING"
	RUNNING      StorageStatus = "RUNNING"
)

// Valid indicates whether the value is a known member of the StorageStatus enum.
func (e StorageStatus) Valid() bool {
	switch e {
	case DELETED:
		return true
	case DELETING:
		return true
	case FAILED:
		return true
	case PROVISIONING:
		return true
	case RUNNING:
		return true
	default:
		return false
	}
}

// Error RFC 9457 compliant error response
type Error struct {
	// Detail Human-readable explanation specific to this occurrence
	Detail *string `json:"detail,omitempty"`

	// Instance Unique identifier for this error occurrence
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int32 `json:"status,omitempty"`

	// Title Short human-readable summary
	Title string `json:"title"`

	// Type Error type code
	Type ErrorType `json:"type"`
}

// ErrorType Error type code
type ErrorType string

// Health Health status singleton resource
type Health struct {
	// Path Canonical path of the resource
	//
	// Example: health
	Path *string `json:"path,omitempty"`

	// Status Health status
	//
	// Example: healthy
	Status string `json:"status"`

	// Type Resource type identifier
	//
	// Example: storage-service-provider.dcm.io/health
	Type *string `json:"type,omitempty"`

	// Uptime Seconds since the service provider started
	//
	// Example: 3600
	Uptime *int `json:"uptime,omitempty"`

	// Version Service provider build version
	//
	// Example: 1.0.0
	Version *string `json:"version,omitempty"`
}

// ProviderHints Provider-specific hints from the catalog
type ProviderHints map[string]interface{}

// StorageSpec Storage specification for creating a volume (implements the portable storage service type)
type StorageSpec struct {
	// Capacity Requested storage capacity (e.g., "100Gi")
	//
	// Example: 100Gi
	Capacity string `json:"capacity"`

	// Metadata Resource metadata for identification
	Metadata VolumeMetadata `json:"metadata"`

	// ProviderHints Provider-specific hints from the catalog
	ProviderHints *ProviderHints `json:"provider_hints,omitempty"`

	// ServiceType Service type identifier (must be "storage")
	ServiceType StorageSpecServiceType `json:"service_type"`
}

// StorageSpecServiceType Service type identifier (must be "storage")
type StorageSpecServiceType string

// StorageStatus Current status of the storage instance (CloudEvents payload uses this enum)
type StorageStatus string

// Volume Volume resource representing a storage instance
type Volume struct {
	// CreateTime Timestamp when the volume was created
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Id DCM instance ID (dcm-instance-id label)
	//
	// Example: app-data-volume
	Id *string `json:"id,omitempty"`

	// Path Resource path identifier
	//
	// Example: volumes/app-data-volume
	Path *string `json:"path,omitempty"`

	// Spec Storage specification for creating a volume (implements the portable storage service type)
	Spec   StorageSpec    `json:"spec"`
	Status *StorageStatus `json:"status,omitempty"`

	// UpdateTime Timestamp when the volume was last updated
	UpdateTime *time.Time `json:"update_time,omitempty"`
}

// VolumeList Paginated list of volume instances
type VolumeList struct {
	// NextPageToken Token for retrieving the next page of results
	NextPageToken *string   `json:"next_page_token,omitempty"`
	Volumes       *[]Volume `json:"volumes,omitempty"`
}

// VolumeMetadata Resource metadata for identification
type VolumeMetadata struct {
	// Labels Custom key-value pairs for tagging and filtering
	Labels *map[string]string `json:"labels,omitempty"`

	// Name DCM instance ID (AEP-122)
	Name string `json:"name"`

	// Namespace Platform namespace where the volume was created
	Namespace *string `json:"namespace,omitempty"`

	// StorageClass Storage class name bound to the volume
	StorageClass *string `json:"storage_class,omitempty"`

	// VolumeName Bound backend volume name when available
	VolumeName *string `json:"volume_name,omitempty"`
}

// VolumeIdPath defines model for VolumeIdPath.
type VolumeIdPath = string

// ListVolumesParams defines parameters for ListVolumes.
type ListVolumesParams struct {
	// MaxPageSize Maximum number of resources per page
	MaxPageSize *int32 `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`

	// PageToken Token for the next page of results
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// CreateVolumeParams defines parameters for CreateVolume.
type CreateVolumeParams struct {
	// Id Optional client-specified DCM instance ID. When provided, it MUST
	// match spec.metadata.name. When omitted, the instance ID is taken from
	// spec.metadata.name (AEP-122).
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// CreateVolumeJSONRequestBody defines body for CreateVolume for application/json ContentType.
type CreateVolumeJSONRequestBody = Volume
