// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	. "github.com/dcm-project/environment-agent/api/v1alpha1"
	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetHealth Health check
	//
	// Liveness health check for the Environment Agent.
	//
	// Corresponds with GET /health (the `GetHealth` operationId).
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListProviders List all Service Providers
	//
	// Returns all registered Service Providers (both embedded and external)
	// including their current health status.
	//
	// Corresponds with GET /providers (the `ListProviders` operationId).
	ListProviders(ctx context.Context, params *ListProvidersParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateProviderWithBody Register an external Service Provider
	//
	// Register an external Service Provider with the agent.
	// Registration is idempotent (name as natural key, create-or-update).
	// Only one SP — embedded or external — may serve a given service type
	// per agent. If the requested service type is already served by another
	// SP, registration is rejected with 409 Conflict.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /providers (the `CreateProvider` operationId).
	CreateProviderWithBody(ctx context.Context, params *CreateProviderParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateProvider Register an external Service Provider
	//
	// Register an external Service Provider with the agent.
	// Registration is idempotent (name as natural key, create-or-update).
	// Only one SP — embedded or external — may serve a given service type
	// per agent. If the requested service type is already served by another
	// SP, registration is rejected with 409 Conflict.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /providers (the `CreateProvider` operationId).
	CreateProvider(ctx context.Context, params *CreateProviderParams, body CreateProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProvider Get a Service Provider
	//
	// Returns a single registered Service Provider by ID, including its
	// current health status.
	//
	// Corresponds with GET /providers/{provider_id} (the `GetProvider` operationId).
	GetProvider(ctx context.Context, providerId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetHealth Health check
//
// Liveness health check for the Environment Agent.
//
// Corresponds with GET /health (the `GetHealth` operationId).
func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListProviders List all Service Providers
//
// Returns all registered Service Providers (both embedded and external)
// including their current health status.
//
// Corresponds with GET /providers (the `ListProviders` operationId).
func (c *Client) ListProviders(ctx context.Context, params *ListProvidersParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListProvidersRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateProviderWithBody Register an external Service Provider
//
// Register an external Service Provider with the agent.
// Registration is idempotent (name as natural key, create-or-update).
// Only one SP — embedded or external — may serve a given service type
// per agent. If the requested service type is already served by another
// SP, registration is rejected with 409 Conflict.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /providers (the `CreateProvider` operationId).
func (c *Client) CreateProviderWithBody(ctx context.Context, params *CreateProviderParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateProviderRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateProvider Register an external Service Provider
//
// Register an external Service Provider with the agent.
// Registration is idempotent (name as natural key, create-or-update).
// Only one SP — embedded or external — may serve a given service type
// per agent. If the requested service type is already served by another
// SP, registration is rejected with 409 Conflict.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /providers (the `CreateProvider` operationId).
func (c *Client) CreateProvider(ctx context.Context, params *CreateProviderParams, body CreateProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateProviderRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetProvider Get a Service Provider
//
// Returns a single registered Service Provider by ID, including its
// current health status.
//
// Corresponds with GET /providers/{provider_id} (the `GetProvider` operationId).
func (c *Client) GetProvider(ctx context.Context, providerId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProviderRequest(c.Server, providerId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetHealthRequest constructs an http.Request for the GetHealth method
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListProvidersRequest constructs an http.Request for the ListProviders method
func NewListProvidersRequest(server string, params *ListProvidersParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/providers")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.MaxPageSize != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "max_page_size", *params.MaxPageSize, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PageToken != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page_token", *params.PageToken, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateProviderRequest calls the generic CreateProvider builder with application/json body
func NewCreateProviderRequest(server string, params *CreateProviderParams, body CreateProviderJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateProviderRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreateProviderRequestWithBody constructs an http.Request for the CreateProvider method, with any body, and a specified content type
func NewCreateProviderRequestWithBody(server string, params *CreateProviderParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/providers")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Id != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "id", *params.Id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetProviderRequest constructs an http.Request for the GetProvider method
func NewGetProviderRequest(server string, providerId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "provider_id", providerId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/providers/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetHealthWithResponse Health check
	//
	// Liveness health check for the Environment Agent.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /health (the `GetHealth` operationId).
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// ListProvidersWithResponse List all Service Providers
	//
	// Returns all registered Service Providers (both embedded and external)
	// including their current health status.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /providers (the `ListProviders` operationId).
	ListProvidersWithResponse(ctx context.Context, params *ListProvidersParams, reqEditors ...RequestEditorFn) (*ListProvidersResponse, error)

	// CreateProviderWithBodyWithResponse Register an external Service Provider
	//
	// Register an external Service Provider with the agent.
	// Registration is idempotent (name as natural key, create-or-update).
	// Only one SP — embedded or external — may serve a given service type
	// per agent. If the requested service type is already served by another
	// SP, registration is rejected with 409 Conflict.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /providers (the `CreateProvider` operationId).
	CreateProviderWithBodyWithResponse(ctx context.Context, params *CreateProviderParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateProviderResponse, error)

	// CreateProviderWithResponse Register an external Service Provider
	//
	// Register an external Service Provider with the agent.
	// Registration is idempotent (name as natural key, create-or-update).
	// Only one SP — embedded or external — may serve a given service type
	// per agent. If the requested service type is already served by another
	// SP, registration is rejected with 409 Conflict.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /providers (the `CreateProvider` operationId).
	CreateProviderWithResponse(ctx context.Context, params *CreateProviderParams, body CreateProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateProviderResponse, error)

	// GetProviderWithResponse Get a Service Provider
	//
	// Returns a single registered Service Provider by ID, including its
	// current health status.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /providers/{provider_id} (the `GetProvider` operationId).
	GetProviderWithResponse(ctx context.Context, providerId string, reqEditors ...RequestEditorFn) (*GetProviderResponse, error)
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Health
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *Error
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetHealthResponse) GetJSON200() *Health {
	return r.JSON200
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r GetHealthResponse) GetApplicationproblemJSON400() *Error {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r GetHealthResponse) GetApplicationproblemJSON401() *Error {
	return r.ApplicationproblemJSON401
}

// GetBody returns the raw response body bytes
func (r GetHealthResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListProvidersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ProviderList
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *Error
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Error
	// ApplicationproblemJSON503 the response for an HTTP 503 `application/problem+json` response
	ApplicationproblemJSON503 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListProvidersResponse) GetJSON200() *ProviderList {
	return r.JSON200
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r ListProvidersResponse) GetApplicationproblemJSON400() *Error {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r ListProvidersResponse) GetApplicationproblemJSON401() *Error {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON503 returns the response for an HTTP 503 `application/problem+json` response
func (r ListProvidersResponse) GetApplicationproblemJSON503() *Error {
	return r.ApplicationproblemJSON503
}

// GetBody returns the raw response body bytes
func (r ListProvidersResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListProvidersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListProvidersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListProvidersResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateProviderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Provider
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *Provider
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *Error
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Error
	// ApplicationproblemJSON409 the response for an HTTP 409 `application/problem+json` response
	ApplicationproblemJSON409 *Error
	// ApplicationproblemJSON422 the response for an HTTP 422 `application/problem+json` response
	ApplicationproblemJSON422 *Error
	// ApplicationproblemJSON503 the response for an HTTP 503 `application/problem+json` response
	ApplicationproblemJSON503 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r CreateProviderResponse) GetJSON200() *Provider {
	return r.JSON200
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreateProviderResponse) GetJSON201() *Provider {
	return r.JSON201
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r CreateProviderResponse) GetApplicationproblemJSON400() *Error {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r CreateProviderResponse) GetApplicationproblemJSON401() *Error {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON409 returns the response for an HTTP 409 `application/problem+json` response
func (r CreateProviderResponse) GetApplicationproblemJSON409() *Error {
	return r.ApplicationproblemJSON409
}

// GetApplicationproblemJSON422 returns the response for an HTTP 422 `application/problem+json` response
func (r CreateProviderResponse) GetApplicationproblemJSON422() *Error {
	return r.ApplicationproblemJSON422
}

// GetApplicationproblemJSON503 returns the response for an HTTP 503 `application/problem+json` response
func (r CreateProviderResponse) GetApplicationproblemJSON503() *Error {
	return r.ApplicationproblemJSON503
}

// GetBody returns the raw response body bytes
func (r CreateProviderResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateProviderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateProviderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateProviderResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetProviderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Provider
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *Error
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Error
	// ApplicationproblemJSON404 the response for an HTTP 404 `application/problem+json` response
	ApplicationproblemJSON404 *Error
	// ApplicationproblemJSON503 the response for an HTTP 503 `application/problem+json` response
	ApplicationproblemJSON503 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetProviderResponse) GetJSON200() *Provider {
	return r.JSON200
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r GetProviderResponse) GetApplicationproblemJSON400() *Error {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r GetProviderResponse) GetApplicationproblemJSON401() *Error {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON404 returns the response for an HTTP 404 `application/problem+json` response
func (r GetProviderResponse) GetApplicationproblemJSON404() *Error {
	return r.ApplicationproblemJSON404
}

// GetApplicationproblemJSON503 returns the response for an HTTP 503 `application/problem+json` response
func (r GetProviderResponse) GetApplicationproblemJSON503() *Error {
	return r.ApplicationproblemJSON503
}

// GetBody returns the raw response body bytes
func (r GetProviderResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetProviderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProviderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetProviderResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetHealthWithResponse Health check
//
// Liveness health check for the Environment Agent.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /health (the `GetHealth` operationId).
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// ListProvidersWithResponse List all Service Providers
//
// Returns all registered Service Providers (both embedded and external)
// including their current health status.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /providers (the `ListProviders` operationId).
func (c *ClientWithResponses) ListProvidersWithResponse(ctx context.Context, params *ListProvidersParams, reqEditors ...RequestEditorFn) (*ListProvidersResponse, error) {
	rsp, err := c.ListProviders(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListProvidersResponse(rsp)
}

// CreateProviderWithBodyWithResponse Register an external Service Provider
//
// Register an external Service Provider with the agent.
// Registration is idempotent (name as natural key, create-or-update).
// Only one SP — embedded or external — may serve a given service type
// per agent. If the requested service type is already served by another
// SP, registration is rejected with 409 Conflict.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /providers (the `CreateProvider` operationId).
func (c *ClientWithResponses) CreateProviderWithBodyWithResponse(ctx context.Context, params *CreateProviderParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateProviderResponse, error) {
	rsp, err := c.CreateProviderWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateProviderResponse(rsp)
}

// CreateProviderWithResponse Register an external Service Provider
//
// Register an external Service Provider with the agent.
// Registration is idempotent (name as natural key, create-or-update).
// Only one SP — embedded or external — may serve a given service type
// per agent. If the requested service type is already served by another
// SP, registration is rejected with 409 Conflict.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /providers (the `CreateProvider` operationId).
func (c *ClientWithResponses) CreateProviderWithResponse(ctx context.Context, params *CreateProviderParams, body CreateProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateProviderResponse, error) {
	rsp, err := c.CreateProvider(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateProviderResponse(rsp)
}

// GetProviderWithResponse Get a Service Provider
//
// Returns a single registered Service Provider by ID, including its
// current health status.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /providers/{provider_id} (the `GetProvider` operationId).
func (c *ClientWithResponses) GetProviderWithResponse(ctx context.Context, providerId string, reqEditors ...RequestEditorFn) (*GetProviderResponse, error) {
	rsp, err := c.GetProvider(ctx, providerId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProviderResponse(rsp)
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	}

	return response, nil
}

// ParseListProvidersResponse parses an HTTP response from a ListProvidersWithResponse call
func ParseListProvidersResponse(rsp *http.Response) (*ListProvidersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListProvidersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProviderList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON503 = &dest

	}

	return response, nil
}

// ParseCreateProviderResponse parses an HTTP response from a CreateProviderWithResponse call
func ParseCreateProviderResponse(rsp *http.Response) (*CreateProviderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateProviderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Provider
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Provider
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON503 = &dest

	}

	return response, nil
}

// ParseGetProviderResponse parses an HTTP response from a GetProviderWithResponse call
func ParseGetProviderResponse(rsp *http.Response) (*GetProviderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProviderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Provider
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON503 = &dest

	}

	return response, nil
}
