// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Hvrdhq5lv+raFWfD0mnigJf0id8+Tc2dML/2IRl456ZFdxZomoDOlFJFUllmxPzPPMe82SzdKkLVIFx",
	"Jp3pWSv5EhC6bO3Lb9/kL17Ek5QzYEp63S9eigVOQIEw3/pY4RmWMIzHWC31SAwyEiRVhDOv690w8jkD",
	"RGJgiswJCDTnAqkloNit9HwPHnCSUvC6XrIKKuNE75DqfX2P4URPyH/9SGLP9wR8zoiA2OsqkYHvyWgJ",
	"CbZUKgVCr//jAw7+1Q7e3L5wH4LbL23/dWedj7/8f3/zfE+tUr2/VIKwhbder/PdNq5Zv2D+CxIgeSYi",
	"/SEVIPV92QLh4p6IMKkwi/TFUsFTEIqA2TwSgBV8VCRp2H9CEpAKJym6XwLb4By6xxLZxZoZcy4SrCyP",
	"IDC7aQ7h+D2jq5xDW9f0PRJ/jdCql9klvQQ/XABbaK14fex7CWH5147/fPk8eZG0Uf+ucqnonys32qA7",
	"J1qGmzd48kyZQqTP/JuAudf1fgpLUwmd9oS5glzruXqNwiozcseUvp973Q8Hrrfr1rfbdK19L0vjr9cg",
	"iqVCdoevVaN11RQ/WLbcFrP47J8QKc/3HgIMaZAbSsVMpV5VSuFLxcrXeqOUZgLTqqQ835OELTKKRWW4",
	"tOOIpYtClIEEcUciCFLB70gMohVHSYvwsFinb5Az+jzNjHTimGgOYjquWKu9/iaDz8c3CFPKI6wHjK0A",
	"jpYaCCiJMCIMRVyARFyghFBK7LcX0Fq0fDT1jqae/u+03U6m3ssaPCT4oS7US/xAkiwx595DjDQNX3vw",
	"L6f5waVJ6DFv00w7wZvbD9ogf06aENNYeAOhhBlCFxkWmCn4Wlo720wqadVjz6N1S1814Qav6kpb0YsB",
	"WxC2zwOAmWBJRlMv5VItBMjP1BHMskSfVo5Xjiu5mG93QaSqHzbGC8K0pSJKpEJ8XodkWdMgBg/qY4oX",
	"8FHxT9AgpIkeNjIRoASBO+26NFDolUiv1CcJkBlVskn0+U/dLx5RkMhDQVGvdZthIfDKiGanBC4h4WL1",
	"POO0a/bZ59cZXGL3renxPVFLlDGiKqr79swpb+fo8syZeKOyvrg8e3x79jg5e7wkZ49vydnjhJy9/B8Z",
	"2/8unV9laJegsNbqPd48cVPMvXKvbuVbEyfFM6Byt9Z8qTN3C98zqXiCPsEquMM007EEEdLGRHixMGEe",
	"i9GcUAVmh4a72fB15330z5vRyfOjp8B9+nlvYGtJkSmOGuj5RzYDwUCBRMUsHTWIMryVCAuoRJ3PiwwM",
	"G/bJfgTqnotPz7NxtwhFnM3JIhPNepBy0QSoXCgjygJHFTfYCgxxp63aprzu69PT41MjCfu9U1yDMAUL",
	"EPoed0SSGaFErfY4isqk0i3oTQTD1Lg29/G2iZ87eXdlTVvuTVKs9Uc8Y8prukC5mZP3V8RCrICdIimK",
	"OJNKYMJU3T1FNuA6xF/o2EyDX+EIDlnk3IaJvbnACzg4ZHfTt7VYE1wQsU+br11+sEMaOk4ucMsiMmFp",
	"ptCcAI0twhhLa1LniDMGkf7po1OO2kGFSpdz0c3VEL0QIFPOJASc0dXL1pT9ZoL+Lppm7fZxZPgA5jN0",
	"w9AOZlLrZDFsB1Ms5T0XsR381Q4uuVT1mVwoO+D2y4mzg1M2SFK1QhlThG6lmhKJjDHCFq0p2wj8ykiq",
	"G4Y4TbvyOBKgftWh/ywQ960iXWjJu6h7enJ8pKd5NQC9dZD5qhXc/twNww9/hL/evura/3798Ec31N80",
	"pr4KW68OSkehiBYP0TQXWxrVLp3fYcrt5mtkL8HzkKU51q6NapnE6OOSuDLPvg3GbvY7M9kYR4k8h5xc",
	"IJUNHUugOWxxvkBbtM3sPlr+bxvAtf0V6V+r5YwXSSYVmgGaFjayGaMXiWFThH4HQpr9D6P3dze9liVX",
	"Sa8IvtCdKm/2okxRUdiOW4QAppCtOOgIfmcJx117PBj1h6O3nu9d3YxG9tNvveHFoO/53s3oH6P3/zby",
	"fK8/uBhMBv296ct1CbVbMrE/7M2Yi+C0mgC223l8ejT5VlH0toz2+Gw7w2V3nb/7qPPLy2q5hDD190aP",
	"OhCCi4bY77dz9Obk9BekVYcSzBQCPRPl4IxejAWfUUhQHxQm1PqDd5PJGPXGQ6lhe8r6MCcMYpS6qfp4",
	"2Z2yRzTROq/R/hFNiKKAHu1aqy3occoeg+Lf49b/7pvep9VqhW53GRJ2hymJAywWWaJ16xEN7RCqDJ20",
	"26i+lnEVzHnGYvSIRlwHXfbzSfukYTamGmJXATwQqSR6RD07gIqBk/abhnUpiIRILaogBkZAnzAuxlAx",
	"dtI+blidMZyppcaJyCTZj+imNnLS7qAmztiYzXDEfdTwAwIZBUCP6LSRLRnDd5hQPDMiyhFrc/TUElsJ",
	"Dfs8krt1qov2qo7ne5mgXtdbKpXKbmjqYErg6BOIFgE1b3GxCGMehUuV0FDMI72p8xOVECQ2m9fJeJcl",
	"mCEtLkM/PKQUM2vqecijo2y1JBLxKDIwFUGTfRqLeNIzDOyste8VmFavaV8NkYA5mKNcPZvIkh5rexvU",
	"FKadCRIUa5vITLkRf/3U/3/9foTG9lc0F3hhLKTqibTIXr9pd9B//efrl8hCoiu+aGcB2k/xeGVDQqSW",
	"WKEIZxJiS78h20eu5PRTqO8TFm4jjNIsTAibei3Um0l9dlEDtheOMGPcuEKslCCzTOu44ggjSdiCNhKh",
	"U26J9DKMjO1b0ZoNbYhWcO6fkrMg505TAX2H6zKq6vxWxGPYAtrO62pidvrmTTUta7ebUFhpDGzwRksu",
	"lI+WWmODQmNlliRYrJoobg40NrXLyXeVC9Ky2vn53NcWthclQSq4duqtBVHLbNYifDfiev6hKwu8PXzJ",
	"Jugevq4Guocv3ULcwxdW8uXDj8oxVYcuB5q37z0EWmbBHTb5j+lVDEe/9y6G/d7V25vLwWji+d7o/eS3",
	"9zcjHSj1Lq4Gvf5/DP59eD259nxvPLi6HF5fD9+P+oPR0MVSvZvJu8FoMjzvTczIcDQZXI16F/bH33vD",
	"i97ZxcC73Y4anRZZdW6KCg0Y9ncg85DF5I7EGaY1yzVBF2EIoySjigSbwYj3LOwPGrHfBKBE1k7+gajf",
	"DFG3lMUJaaeaNCDv2PauEWd05a52z01ThgtAEicQmGxqm0znyVtTNtCRPDAlVshuPQOJONtYMseEZgJa",
	"aAQ6QgKd+/uI6S9TZvkUmC1aaMLTgMIdUGRvg+Bzhqk0HJ8TIZU7S7v0GY4+3WMRT5mOErByVTbLwoMa",
	"E1XrsVX2oV12tN2o8L13gGlTz9mO5+7L3kZxVhTD6pXJxtb1OWackQhT27t26Vtlk7IQsrSUHNKx3uVw",
	"qzRXvZQZ154wY/nn2/rRz3CVRc17KynfuNBh7dvi2juh/El+ZGlz0/waIs5iIz1N6hKQIwLlRGheCeux",
	"CrqPX+vgY8eh1SrxrnTzevuQWUZonCefGyzqtNqt9rML8M59FHJ2r2vKAxxDnt29d7KoNuvtUN6qNzZQ",
	"PNQpe/eFEJ/VuXer9PWGjKh4tlmT2lmznmMqa0XrsasjIrvVZh8BzQVPSoEsG0vY8c73QXpLgulGe8F2",
	"TxrdnqunNjV+7S85DhC3byabI2szvpMa/WtJCcIS8XsGYnvz+ruKfX2InI3fRBRFYvYE54kR2VOw3qQj",
	"h/cDXMlqa3kjCw67elPnZFzgSn5zc2GrflooEVaY8kVDX8uy7MmqbaN4Gq/ReOHnCTIv8+2QI8qY/lzQ",
	"vn0pJ5mPEcWywV2NcAK5srqpyEy1Jc4ZuucZjbWaH6K6a1M5mHPXVlE4Mo1C9+Swf36JxjarqBVOXJYR",
	"8aSafIT7MazeYdZH1PyLDmgSzLBpMBedDEQYqrRpI5pJBUKiO4Kn7JzyLB5hRe5g/LY1ZRMd0PbGQzTn",
	"lPJ7iXoDk1azGIu8v8SZNN3OaIVwJLiUqEKNtKETJREwi26OKb0UR0tAR8YFbfLk/v6+hc3Ppozk1srw",
	"Yng+GF0PgqNWu7VUCa1k5d4G4agouubusLCN3nhY8Va5E1z7Hk+B4ZR4Xe+41W6dOM9mNCfEKQnvOpim",
	"S9wJyxdk3S/eAlRTgGKewADCtTc20lamU/sIx9SzstT0lQ0F1mEMY6/rXRCp+pXHatVXsx92vS1hWTKz",
	"IFx22xVHAlQmGDK5mcshUo1a7oHs5wxMqcJJJsEP9q2PJP8yrr54ExvDHGdUed3T9mY55fioWk7ptHUQ",
	"s6/NvfabHxARFpNKtmUCJP3FpCvFG9I9tFfeKFUJ3zZg8wTS5qVGjEftdm66wIxEcWoaCZq6UGdMBlKK",
	"/Q7p2pjnVwYZtnAtiyKQcp5RuspfS0FcaohWxpO99Lh6xKvn0WW7CA0EneE4Tynt2Z3vd3avLN0Qk+C4",
	"QNPQcfz96KgV+DUFp99TCkXNX9qaP7iJvpfXEi0moCooKLwwsXM5dmtKH00P/85dpIYY3Df28Dbxx07v",
	"l/HbXgB6n1qvjiJKgKnAOW2I0bBfe/vdQsO5qVU4TxX7U5YnSCDQPaEULYBpagBhhoZ906m6ssqRgAlq",
	"jD/S7ijoHB2hIicc9lGAckeCIW3FcBd2jo7Cn3JEDEi89QogWQXxbAegmL8SKEX7bZ+kN8KSMcQzHq++",
	"OSJZtdv8k4d1DQk7f9K5O9qi7iEYkhVY/AGBfxUIPGm/+X4UnHM2pyRSKCgDOBMuGXDQAbt55Yg3+rh/",
	"SaB2WFtBzyakXvu7Qsu8OrEnwswEs7nKcqNYmKc0Nu6tofpbUO/KUt+fFAG9y0sr9djHheNEorzst8k4",
	"V0U8X0L0qcI1t+Nelm3+zYdhGQXV9NzejOtQOM8sn/aGds1ub9jEjnJKuPVHbg3x58mex3f2Ik0Q+QOm",
	"cgpOvh8FBTax/A3KXxKDnJo/gUH+kynsbitBsxUa9psw5k80lPb3DU/KBO1HgPLD8v9vWP5bUE+GHu7l",
	"a3M2dz7aV0Mr6nWhsU+3/Y5+YKQ9OSoAQpaZVR4l+DtfTFIyh2gVUbBVTJP5NW5V3mx9u/7vAAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
