// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fvrchu5cn4VFPb8sNczHFIXn5h/spTItZkj0SqJ2iRlal3gTJPE8QwwBjCSuCafJ++RJ0vhMhdyhjSl",
	"eJ1Nlf1HJIhLA9399dcN+AsOeZJyBkxJ3P2CUyJIAgqE+dYnikyJhGF0RdRCt0QgQ0FTRTnDXXzL6OcM",
	"EI2AKTqjINCMC6QWgCI3EnsYHkmSxoC7OFn6lXaqZ0j1vB5mJNEd8l8/0gh7WMDnjAqIcFeJDDwswwUk",
	"xEqpFAg9/vcPxP+j7b+5e+E++Hdf2t7rzjpvf/mvf8MeVstUzy+VoGyO1+t1PtvGNusbzH9BAiTPRKg/",
	"pAKk3i+bI1LsE1EmFWGh3lgqeApCUTCThwKIgo+KJg3zj2kCUpEkRQ8LYBsnhx6IRHawPowZFwlR9ozA",
	"N7PpEyLRexYv8xPa2qaHafQcpVU3s0t7CXm8ADbXVvH62MMJZfnXjvd0/Xx1I2mj/V3nWtE/V3a0IXcu",
	"tAw2d/DVNWUKoV7zbwJmuIt/CkpXCZz1BLmB3Oi+eowiKjN6J3H8foa7Hw4cb8et77blWns4S6PnW1BM",
	"pEJ2huea0brqih/ssdwVvfj0nxAq7OFHn0Dq545ScVOpR5Va+FLx8rWeKI0zQeKqprCHJWXzLCai0lz6",
	"ccjSeaFKX4K4pyH4qeD3NALRisKkRXlQjNM7yA/6PM2MdqKI6hMk8VXFW+32Nw/4/OoWkTjmIdENxleA",
	"hAsNBDENCaIMhVyARFyghMYxtd9eQGve8tAEH02w/nPabicT/LIGDwl5rCv1kjzSJEvMug8QIS3Dcxf+",
	"+2m+cOkSug1vumnHf3P3QTvkz0kTYhoPbxCUMiPoPCOCMAXPlbWzfUilrLrtabJu2asW3OBV3WgrdjFg",
	"c8r2RQAwHazIaIJTLtVcgPwcO4FZlujVyvbKcuUp5tNdUKnqi12ROWXaU1FMpUJ8VodkWbMgBo/qY0rm",
	"8FHxT9CgpLFuNjoRoASFex26NFDokUiP1CsJkFmsZJPq85+6XzBVkMhDQVGPdZMRIcjSqGanBi4h4WL5",
	"NOe0Y/b55/McLrHz1uz4gaoFyhhVFdN9e+aMt3N0eeZcvNFYX1yerd6ercZnq0t6tnpLz1Zjevbyf+Vs",
	"/7dyPsvRLkERbdV7onniuph95VHd6remzphMIZa7reZL/XC38D2TiifoEyz9exJnmktQIS0nIvO5oXks",
	"QjMaKzAzNOzN0ted+9E/b7KTp7Mn3336eS+xtaLIlIQN8vwjm4JgoECiopdmDaKktxIRARXW+TRmYI5h",
	"n+5HoB64+PQ0H3eDUMjZjM4z0WwHKRdNgMqFMqoscFRxg63AEHfWqn0Kd1+fnh6fGk3Y751iG5QpmIPQ",
	"+7inkk5pTNVyT6CodCrDgp5EMBKb0OY+3jWd586zu7auLfcmKdb7Q54xhZs2UE7m9P0MLsQK2CmSopAz",
	"qQShTNXDU2gJ1yHxQnMzDX5FIDhkkAsbhntzQeZwMGV33betWAtcCLHPmm9cfrBDG5onF7hlEZmyNFNo",
	"RiGOLMIYT2sy55AzBqH+6aMzjtpChUmXfdHt9RC9ECBTziT4nMXLl60J+9WQ/i6aZO32cWjOAcxn6AaB",
	"bcyktsmi2TamRMoHLiLb+IttXHCp6j25ULbBzZcLZxsnbJCkaokypmi8lWpKJDLGKJu3JmyD+JVMqhsE",
	"JE278jgUoH7R1H/qi4dWkS605H3YPT05PtLdcA1A7xxkvmr5dz93g+DD78Evd6+69s8vH37vBvqbxtRX",
	"QevVQekoFGzxEEtz3NKYdhn8DjNu118jewmehwzNsXZtTMskRh8X1JV5Dnf596nth/JJ/NyukZkNzQRP",
	"jEpDokjM5+gFCUNIFUQeYlwhEmo+m6WcvWwKnaICa4dsq4BBy0tLFDtscD5Aw4VNGz9akba968b+ivSv",
	"1VrJiySTCk0BTQoH3EwAiqyzif7fg5Bm/sPk/c11r6XgVdErVlUYZvVs9kJYUa7YJkVCAFPIljN0erCz",
	"PuS2fTUY9Yejt9jD17ejkf30a294MehjD9+O/jF6/+8j7OH+4GIwHvT35kY3JY5v6cT+sDcdL5hvNbts",
	"t3PyezT+VhR9W0d7CIHtUaSOnX+xssREgVRWnNr0AyG4aOCUv56jNyenf0faamJKmEKge6Ic9NGLK8Gn",
	"MSSoD4rQ2MaZd+PxFepdDaUOBxPWhxllEGmfNl316rI7YSs01uauo8gKjamKAa3sWGsoaDVhK7/4t9r6",
	"677peVqtVuBmlwFl9ySmkU/EPEu0Wa3Q0DahStNJu43qYxlX/oxnLEIrNOKazNnPJ+2Tht4k1tC99OGR",
	"SiXRCvVsAyoaTtpvGsalIBIqtZb8CBgFvcJV0YaKtpP2ccPojJFMLTREhCZ5X6HbWstJu4OaTsZyQXMi",
	"7qNGHhDIGABaodPGY8kYuSc0JlOjohysNltPrbAVytnnodxtU12013SwhzMR4y5eKJXKbmDqa0qQ8BOI",
	"FgU1a3ExDyIeBguVxIGYhXpSF38q1CYyk9fFeJclhCGtLiM/PKYxYdbLi5CjOFILKhEPQ4NQITT5jvGI",
	"rwaFge219nABZ/Va+fUQCZiBWcrVyaks5bG+tyFNUWHNBPWLsU1iptyov77qv928H6Er+yuaCTI3HlIN",
	"Qlplr9+0O+i//+v1S2TR0BV1dJwAHaJ4tLRUE6kFUSgkmYTIym/E9pDDo58CvZ+giBhBmGZBQtkEt1Bv",
	"KvXaRW3ZbjgkTIf2KSCilKDTTNu44oggSdk8bhRCp/LSMgJkfN+q1kxoqV9xcv+UnPn56TQV5ndELWOq",
	"LmSFPNrQBmWq87qa8J2+eVNN99rtpnxJaQxsCEQLLpSHFtpi/cJiZZYkRCybJG7mGJvW5fS7zBVpj9qF",
	"+DzMFr4XJn4quI7nrTlVi2zaonw34mLv0JEF3h4+ZBN0Dx9XA93Dh24h7uEDK3n44UvlmKpZy4Hu7eFH",
	"X+vMvycmrzJ3IMPRb72LYb93/fb2cjAaYw+P3o9/fX870hypd3E96PX/c/Afw5vxDfbw1eD6cnhzM3w/",
	"6g9GQ0ejerfjd4PReHjeG5uW4Wg8uB71LuyPv/WGF72ziwG+2yaMzoqsOTcRQgOG/R3IPGQRvadRRuKa",
	"5xq+RRkiKMliRf1NMoKfhP1+I/Yb7kllbeUfiPrNEHXLWJySdppJA/Je2TtxxFm8dFt74OayhwtAkiTg",
	"m0RqW0wXyVsTNtAkHpgSS2SnnoJEnG0MmREaZwJaaASaIUGSqqWHmP4yYfacfDNFC4156sdwDzGyu0Hw",
	"OSOxNCc+o0Iqt5YO6VMSfnogIpowzRKIctU7e4QHXXhUvcdW74d22NH2BYiH3wGJm+6ybXsevuxuFGdF",
	"ka1e8Wy8Ej8njDMa6oSdqEWeuVUmKQssCyvJITfhuwJuVeZqlDLtOhJmLP98V1/6CaGyqKVv5eMbGzrs",
	"WrjY9k4o/+p5ZGnzZfwNhJxFRnta1AUgJ0RRPdFnJWzEKuQ+fq3Jx45Fq9XnXZnmzfYi04zGUZ53bhxR",
	"p9VutZ9c2Hfho9Cze7VTLuAO5MmvApwuqo8AbFP+BMD4QPEAqHwTUCjxSS8C3Ki1eQBE2Yy7Uqsiobk8",
	"cM+Q+ueXOhVyO9hMehxDCHlSJQ7B/vXrt056iZptaDBKCCPm0qmobiLKUOXqJowzqUBIdE/JhJ3HPItG",
	"RNF7uHrbmrCxDka9qyGa8TjmDxL1BoYSs4iIvObMmTQ3IOESkVBwKVFFGmlhL6YhMPsiyh1KLyXhAtCR",
	"MZ/NM3l4eGgR87NJAd1YGVwMzwejm4F/1Gq3dE5YYdR4Q3BU1EpyU77Kz6R3NaxYWm7Aaw/zFBhJKe7i",
	"41a7deKs0oBUQFIa3HdInC5IJyhflXS/4DmoJnAx1+KASO3eXdqCUmov5k0umqXmrslIYC+jhhHu4gsq",
	"Vb/ygKX6ku7DrvtmliVTEO763d3AKY4EqEwwZHiVi/8pmReP5j5nYNIMp5mEPNr7f0n/MG5avJOLYEay",
	"WOHuaXszFTo+qqZCnbYGoH1XX2uv+VEBZRGtMCUDbvqLoRrFu7I9slfeLVQF34Yj8yzKckqjxqN2O3dd",
	"nd10v2CSmvqfli7QbEe3lfMdUmw1TzIMMmyhaxaGIOUsi+Nl/oICotJCtDGe7JXH5RKvniaXrQA2CHRG",
	"opwO2rU732/tXpl2UUNOXJAwchx/PzlqxTktwen31EJRr5O2Xgeuo4fzOoDFBFQFBUXmJu6VbXcmbWl6",
	"DHRubuERQQweGkvvm/hju/fLt3J7Aai41gljCkzllzoQoWG/9h60hYYzk2e4SBV5E5aTG9ApYByjOTAt",
	"DSDC0LBvqszX1jh0qiVdPNLhyO8cHaGCzw37yEd5ICGQtiK4DzpHR8FPOSL6NNq6GUyWfjTdASjm5XCp",
	"2m/7TLURlowjnvFo+c0RyZrd5jPodQ0JO3/SujtuM9zjECQrsPgDAv8qEHjSfvP9JDjnbBbTUCG/JHCG",
	"LhlwIIl7+UQ27mD+kkDtsLaCnk1IvfZ2Ucs8s9jDMDPBbPlhsZHouwTdse8aqr8F9a5M0/8kBvSuSIu8",
	"HZkllShP2TcPzlUAzhcQfqqcmptx75FtvgM3RxaDanqCa9o1Fc6vXb4eDe2Y3dGw6TjKLsHWf3xp4J8n",
	"ex7k2I00QeQPmMolOPl+EhTYxPL7478kBjkz/woGeV9NYXd7CZou0bDfhDF/oqO0vy89KRO0HwTlh+f/",
	"//D8t6C+Sj3cg7XmbO58tK+GVtTrAuOfbvodtfxQR3JUAIQsM6ucJXg7HzrFdAbhMozBVjFN5tc4Vbmz",
	"9d36fwIAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
