// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
	"time"
)

// Defines values for DatabaseEngine.
const (
	Postgresql DatabaseEngine = "postgresql"
)

// Valid indicates whether the value is a known member of the DatabaseEngine enum.
func (e DatabaseEngine) Valid() bool {
	switch e {
	case Postgresql:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseNetworkVisibility.
const (
	External DatabaseNetworkVisibility = "external"
	Internal DatabaseNetworkVisibility = "internal"
)

// Valid indicates whether the value is a known member of the DatabaseNetworkVisibility enum.
func (e DatabaseNetworkVisibility) Valid() bool {
	switch e {
	case External:
		return true
	case Internal:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseSpecServiceType.
const (
	DatabaseSpecServiceTypeDatabase DatabaseSpecServiceType = "database"
)

// Valid indicates whether the value is a known member of the DatabaseSpecServiceType enum.
func (e DatabaseSpecServiceType) Valid() bool {
	switch e {
	case DatabaseSpecServiceTypeDatabase:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseStatus.
const (
	DELETED DatabaseStatus = "DELETED"
	FAILED  DatabaseStatus = "FAILED"
	PENDING DatabaseStatus = "PENDING"
	RUNNING DatabaseStatus = "RUNNING"
	UNKNOWN DatabaseStatus = "UNKNOWN"
)

// Valid indicates whether the value is a known member of the DatabaseStatus enum.
func (e DatabaseStatus) Valid() bool {
	switch e {
	case DELETED:
		return true
	case FAILED:
		return true
	case PENDING:
		return true
	case RUNNING:
		return true
	case UNKNOWN:
		return true
	default:
		return false
	}
}

// Defines values for ErrorType.
const (
	ALREADYEXISTS    ErrorType = "https://dcm-project.github.io/problems/already-exists"
	INTERNAL         ErrorType = "https://dcm-project.github.io/problems/internal"
	INVALIDARGUMENT  ErrorType = "https://dcm-project.github.io/problems/invalid-argument"
	NOTFOUND         ErrorType = "https://dcm-project.github.io/problems/not-found"
	PERMISSIONDENIED ErrorType = "https://dcm-project.github.io/problems/permission-denied"
	UNAUTHENTICATED  ErrorType = "https://dcm-project.github.io/problems/unauthenticated"
	UNAVAILABLE      ErrorType = "https://dcm-project.github.io/problems/unavailable"
)

// Valid indicates whether the value is a known member of the ErrorType enum.
func (e ErrorType) Valid() bool {
	switch e {
	case ALREADYEXISTS:
		return true
	case INTERNAL:
		return true
	case INVALIDARGUMENT:
		return true
	case NOTFOUND:
		return true
	case PERMISSIONDENIED:
		return true
	case UNAUTHENTICATED:
		return true
	case UNAVAILABLE:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Healthy   HealthStatus = "healthy"
	Unhealthy HealthStatus = "unhealthy"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Healthy:
		return true
	case Unhealthy:
		return true
	default:
		return false
	}
}

// Database Database resource representing a database instance
type Database struct {
	// CreateTime Timestamp when the database was created
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Id Unique identifier for the database instance
	//
	// Example: my-database
	Id *string `json:"id,omitempty"`

	// Path Resource path identifier
	//
	// Example: databases/my-database
	Path *string `json:"path,omitempty"`

	// Spec Database specification with input fields for creation
	Spec   DatabaseSpec    `json:"spec"`
	Status *DatabaseStatus `json:"status,omitempty"`

	// UpdateTime Timestamp when the database was last updated
	UpdateTime *time.Time `json:"update_time,omitempty"`
}

// DatabaseCpu CPU allocation for each replica in cores or millicores (e.g., "2", "500m")
type DatabaseCpu struct {
	// Max Maximum allowed CPU for each replica in cores or millicores (e.g., "2", "750m")
	//
	// Example: 750m
	Max string `json:"max"`

	// Min Minimum guaranteed CPU for each replica in cores or millicores (e.g., "1", "500m")
	//
	// Example: 500m
	Min                  string                 `json:"min"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// DatabaseEngine Database engine (e.g. "postgresql")
type DatabaseEngine string

// DatabaseList Paginated list of database instances
type DatabaseList struct {
	// NextPageToken Token for retrieving the next page of results
	NextPageToken *string     `json:"next_page_token,omitempty"`
	Results       *[]Database `json:"results,omitempty"`
}

// DatabaseMemory Memory allocation for each replica
type DatabaseMemory struct {
	// Max Maximum allowed memory for each replica with unit (e.g., "1GB", "512MB")
	Max string `json:"max"`

	// Min Minimum guaranteed memory for each replica with unit (e.g., "1GB", "512MB")
	Min                  string                 `json:"min"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// DatabaseMetadata Resource metadata for identification
type DatabaseMetadata struct {
	// Labels Custom key-value pairs for tagging and filtering
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Resource name identifier
	Name string `json:"name"`

	// Namespace Kubernetes namespace where resources are created
	Namespace *string `json:"namespace,omitempty"`
}

// DatabaseNetwork Network configuration
type DatabaseNetwork struct {
	// Port Port for database to listen on
	Port *int `json:"port,omitempty"`

	// Visibility Database visibility
	Visibility           *DatabaseNetworkVisibility `json:"visibility,omitempty"`
	AdditionalProperties map[string]interface{}     `json:"-"`
}

// DatabaseNetworkVisibility Database visibility
type DatabaseNetworkVisibility string

// DatabaseReplicas Database replica count
type DatabaseReplicas = int

// DatabaseResources CPU and memory resource constraints
type DatabaseResources struct {
	// Cpu CPU allocation for each replica in cores or millicores (e.g., "2", "500m")
	Cpu DatabaseCpu `json:"cpu"`

	// Memory Memory allocation for each replica
	Memory DatabaseMemory `json:"memory"`

	// Storage Storage allocation for each replica with units (e.g., "100GB", "2TB")
	Storage              *DatabaseStorage       `json:"storage,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// DatabaseSpec Database specification with input fields for creation
type DatabaseSpec struct {
	// ConnectionString database connection URI (response-only).
	// Format: <scheme>://<username>:<password>@<hostname>:<port>/<database>
	// Empty until the database is running.
	//
	//
	// Example: postgresql://app:s3cret@pg-db-rw.databases.svc:5432/app
	ConnectionString *string `json:"connection_string,omitempty"`

	// Engine Database engine (e.g. "postgresql")
	Engine DatabaseEngine `json:"engine"`

	// Metadata Resource metadata for identification
	Metadata DatabaseMetadata `json:"metadata"`

	// Network Network configuration
	Network *DatabaseNetwork `json:"network,omitempty"`

	// ProviderHints Optional provider-specific hints from the catalog (accepted, not acted upon)
	ProviderHints *map[string]interface{} `json:"provider_hints,omitempty"`

	// Replicas Database replica count
	Replicas *DatabaseReplicas `json:"replicas,omitempty"`

	// Resources CPU and memory resource constraints
	Resources DatabaseResources `json:"resources"`

	// ServiceType Service type identifier (must be "database")
	ServiceType DatabaseSpecServiceType `json:"service_type"`

	// Version Database version (e.g. "18", "latest")
	Version *DatabaseVersion `json:"version,omitempty"`
}

// DatabaseSpecServiceType Service type identifier (must be "database")
type DatabaseSpecServiceType string

// DatabaseStatus Current status of the database instance
type DatabaseStatus string

// DatabaseStorage Storage allocation for each replica with units (e.g., "100GB", "2TB")
type DatabaseStorage = string

// DatabaseVersion Database version (e.g. "18", "latest")
type DatabaseVersion = string

// Error RFC 9457 compliant error response (Problem Details for HTTP APIs).
//
// Defined problem types:
// | Type URI | Title | HTTP Status |
// |----------|-------|-------------|
// | .../problems/invalid-argument | Invalid argument | 400 |
// | .../problems/not-found | Not found | 404 |
// | .../problems/already-exists | Already exists | 409 |
// | .../problems/permission-denied | Permission denied | 403 |
// | .../problems/unauthenticated | Unauthenticated | 401 |
// | .../problems/internal | Internal Server Error | 500 |
// | .../problems/unavailable | Service unavailable | 503 |
type Error struct {
	// Detail Human readable explanation specific to this occurrence
	Detail *string `json:"detail,omitempty"`

	// Errors Present only when two or more same-type validation errors occur.
	// Each entry describes one validation failure. Never empty, never
	// single-entry. Top-level detail equals the first entry for backward
	// compatibility.
	Errors *Errors `json:"errors,omitempty"`

	// Instance URI reference for this specific error occurrence
	Instance *string `json:"instance,omitempty"`

	// Pointer JSON Pointer fragment identifier (RFC 6901 §6) locating the request body field that caused this error, e.g. "#/spec/resources/cpu/min". Absent when the error cannot be attributed to a single request body field or is not a validation error.
	Pointer *string `json:"pointer,omitempty"`

	// Status HTTP status code
	Status *int16 `json:"status,omitempty"`

	// Title Short, human-readable summary
	Title string `json:"title"`

	// Type URI reference identifying the error type
	Type ErrorType `json:"type"`
}

// ErrorType URI reference identifying the error type
type ErrorType string

// ErrorDetail Individual validation error within a multi-error response
type ErrorDetail struct {
	// Detail Human-readable explanation of this validation error
	Detail string `json:"detail"`

	// Pointer JSON Pointer fragment identifier (RFC 6901 §6) locating the request body field that caused this error, e.g. "#/spec/resources/cpu/min". Absent when the error cannot be attributed to a single request body field or is not a validation error.
	Pointer *string `json:"pointer,omitempty"`
}

// Errors Present only when two or more same-type validation errors occur.
// Each entry describes one validation failure. Never empty, never
// single-entry. Top-level detail equals the first entry for backward
// compatibility.
type Errors = []ErrorDetail

// Health Health status singleton resource
type Health struct {
	// Path Canonical path of the resource
	//
	// Example: health
	Path *string `json:"path,omitempty"`

	// Status Health status
	//
	// Example: healthy
	Status HealthStatus `json:"status"`

	// Type Resource type identifier
	//
	// Example: cnpg-database-service-provider.dcm.io/health
	Type *string `json:"type,omitempty"`

	// Uptime Seconds since the service provider started
	//
	// Example: 3600
	Uptime *int `json:"uptime,omitempty"`

	// Version Service provider build version
	//
	// Example: 1.0.0
	Version *string `json:"version,omitempty"`
}

// HealthStatus Health status
//
// Example: healthy
type HealthStatus string

// DatabaseIdPath defines model for DatabaseIdPath.
type DatabaseIdPath = string

// ListDatabasesParams defines parameters for ListDatabases.
type ListDatabasesParams struct {
	// MaxPageSize Maximum number of resources to return in a single page
	MaxPageSize *int32 `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`

	// PageToken Token indicating the starting point for the page
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// CreateDatabaseParams defines parameters for CreateDatabase.
type CreateDatabaseParams struct {
	// Id Optional client-specified ID for the database. If not provided,
	// the server will generate an ID.
	//
	// Requirements follow AEP-122 Resource ID - https://aep.dev/122/#resource-id
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// CreateDatabaseJSONRequestBody defines body for CreateDatabase for application/json ContentType.
type CreateDatabaseJSONRequestBody = Database

// Getter for additional properties for DatabaseCpu. Returns the specified
// element and whether it was found
func (a DatabaseCpu) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for DatabaseCpu
func (a *DatabaseCpu) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for DatabaseCpu to handle AdditionalProperties
func (a *DatabaseCpu) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["max"]; found {
		err = json.Unmarshal(raw, &a.Max)
		if err != nil {
			return fmt.Errorf("error reading 'max': %w", err)
		}
		delete(object, "max")
	}

	if raw, found := object["min"]; found {
		err = json.Unmarshal(raw, &a.Min)
		if err != nil {
			return fmt.Errorf("error reading 'min': %w", err)
		}
		delete(object, "min")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for DatabaseCpu to handle AdditionalProperties
func (a DatabaseCpu) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["max"], err = json.Marshal(a.Max)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'max': %w", err)
	}

	object["min"], err = json.Marshal(a.Min)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'min': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for DatabaseMemory. Returns the specified
// element and whether it was found
func (a DatabaseMemory) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for DatabaseMemory
func (a *DatabaseMemory) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for DatabaseMemory to handle AdditionalProperties
func (a *DatabaseMemory) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["max"]; found {
		err = json.Unmarshal(raw, &a.Max)
		if err != nil {
			return fmt.Errorf("error reading 'max': %w", err)
		}
		delete(object, "max")
	}

	if raw, found := object["min"]; found {
		err = json.Unmarshal(raw, &a.Min)
		if err != nil {
			return fmt.Errorf("error reading 'min': %w", err)
		}
		delete(object, "min")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for DatabaseMemory to handle AdditionalProperties
func (a DatabaseMemory) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["max"], err = json.Marshal(a.Max)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'max': %w", err)
	}

	object["min"], err = json.Marshal(a.Min)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'min': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for DatabaseNetwork. Returns the specified
// element and whether it was found
func (a DatabaseNetwork) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for DatabaseNetwork
func (a *DatabaseNetwork) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for DatabaseNetwork to handle AdditionalProperties
func (a *DatabaseNetwork) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["port"]; found {
		err = json.Unmarshal(raw, &a.Port)
		if err != nil {
			return fmt.Errorf("error reading 'port': %w", err)
		}
		delete(object, "port")
	}

	if raw, found := object["visibility"]; found {
		err = json.Unmarshal(raw, &a.Visibility)
		if err != nil {
			return fmt.Errorf("error reading 'visibility': %w", err)
		}
		delete(object, "visibility")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for DatabaseNetwork to handle AdditionalProperties
func (a DatabaseNetwork) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Port != nil {
		object["port"], err = json.Marshal(a.Port)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'port': %w", err)
		}
	}

	if a.Visibility != nil {
		object["visibility"], err = json.Marshal(a.Visibility)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'visibility': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for DatabaseResources. Returns the specified
// element and whether it was found
func (a DatabaseResources) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for DatabaseResources
func (a *DatabaseResources) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for DatabaseResources to handle AdditionalProperties
func (a *DatabaseResources) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["cpu"]; found {
		err = json.Unmarshal(raw, &a.Cpu)
		if err != nil {
			return fmt.Errorf("error reading 'cpu': %w", err)
		}
		delete(object, "cpu")
	}

	if raw, found := object["memory"]; found {
		err = json.Unmarshal(raw, &a.Memory)
		if err != nil {
			return fmt.Errorf("error reading 'memory': %w", err)
		}
		delete(object, "memory")
	}

	if raw, found := object["storage"]; found {
		err = json.Unmarshal(raw, &a.Storage)
		if err != nil {
			return fmt.Errorf("error reading 'storage': %w", err)
		}
		delete(object, "storage")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for DatabaseResources to handle AdditionalProperties
func (a DatabaseResources) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["cpu"], err = json.Marshal(a.Cpu)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'cpu': %w", err)
	}

	object["memory"], err = json.Marshal(a.Memory)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'memory': %w", err)
	}

	if a.Storage != nil {
		object["storage"], err = json.Marshal(a.Storage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'storage': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
