package routing

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"math/rand"
	"net/http"
	"net/url"
	"time"

	"github.com/dcm-project/environment-agent/internal/backoff"
	"github.com/dcm-project/environment-agent/internal/provider/store"
)

const (
	idempotencyKeyHeader = "Idempotency-Key"
	maxResponseBodyBytes = 4096
)

// forwarderError represents a status-coded failure generated by the agent
// before it receives a provider response.
type forwarderError struct {
	statusCode int
	message    string
}

func (e *forwarderError) Error() string {
	return fmt.Sprintf("%d %s", e.statusCode, e.message)
}

// EmbeddedHandler provides in-process SP handling for embedded SPs.
type EmbeddedHandler interface {
	CreateResource(ctx context.Context, req CreateResourceRequest) error
	DeleteResource(ctx context.Context, req DeleteResourceRequest) error
}

// Forwarder implements SPForwarder using HTTP for external SPs and
// in-process handlers for embedded SPs.
type Forwarder struct {
	httpClient *http.Client
	embedded   map[string]EmbeddedHandler
	logger     *slog.Logger
}

// ForwarderConfig holds forwarder options.
type ForwarderConfig struct {
	HTTPClient *http.Client
	Embedded   map[string]EmbeddedHandler
	Logger     *slog.Logger
}

// NewForwarder creates a Forwarder. If HTTPClient is nil, http.DefaultClient is used.
func NewForwarder(cfg ForwarderConfig) *Forwarder {
	c := cfg.HTTPClient
	if c == nil {
		c = http.DefaultClient
	}
	e := cfg.Embedded
	if e == nil {
		e = make(map[string]EmbeddedHandler)
	}
	l := cfg.Logger
	if l == nil {
		l = slog.Default()
	}
	return &Forwarder{httpClient: c, embedded: e, logger: l}
}

func (f *Forwarder) CreateResource(ctx context.Context, endpoint string, embedded bool, req CreateResourceRequest) error {
	start := time.Now()
	var err error
	if embedded {
		err = f.createEmbedded(ctx, req)
	} else {
		err = f.createExternal(ctx, endpoint, req)
	}
	f.logDispatch("create", req.ResourceID, req.ServiceType, req.EventID, embedded, time.Since(start), err)
	return err
}

func (f *Forwarder) DeleteResource(ctx context.Context, endpoint string, embedded bool, req DeleteResourceRequest) error {
	start := time.Now()
	var err error
	if embedded {
		err = f.deleteEmbedded(ctx, req)
	} else {
		err = f.deleteExternal(ctx, endpoint, req)
	}
	f.logDispatch("delete", req.ResourceID, req.ServiceType, req.EventID, embedded, time.Since(start), err)
	return err
}

// logDispatch logs the outcome of a single SP dispatch. It never includes
// request specs or response bodies — only correlation and timing metadata.
func (f *Forwarder) logDispatch(operation, resourceID, serviceType, ceID string, embedded bool, duration time.Duration, err error) {
	kind := "external"
	if embedded {
		kind = "embedded"
	}
	attrs := make([]any, 0, 16)
	attrs = append(attrs,
		"resource_id", resourceID, "service_type", serviceType, "ce_id", ceID,
		"operation", operation, "provider_kind", kind, "duration", duration,
	)
	if err == nil {
		f.logger.Info("SP dispatch completed", attrs...)
		return
	}
	f.logger.Warn("SP dispatch failed", append(attrs, SafeErrorAttrs(err)...)...)
}

func (f *Forwarder) createEmbedded(ctx context.Context, req CreateResourceRequest) error {
	h, ok := f.embedded[req.ServiceType]
	if !ok {
		return &forwarderError{statusCode: http.StatusServiceUnavailable, message: "no embedded handler for service type: " + req.ServiceType}
	}
	return h.CreateResource(ctx, req)
}

func (f *Forwarder) deleteEmbedded(ctx context.Context, req DeleteResourceRequest) error {
	h, ok := f.embedded[req.ServiceType]
	if !ok {
		return &forwarderError{statusCode: http.StatusServiceUnavailable, message: "no embedded handler for service type: " + req.ServiceType}
	}
	return h.DeleteResource(ctx, req)
}

func (f *Forwarder) createExternal(ctx context.Context, endpoint string, req CreateResourceRequest) error {
	body, err := json.Marshal(req.Spec)
	if err != nil {
		return &forwarderError{statusCode: http.StatusBadRequest, message: "failed to marshal spec: " + err.Error()}
	}
	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint, bytes.NewReader(body))
	if err != nil {
		return fmt.Errorf("creating POST request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set(idempotencyKeyHeader, req.EventID)

	return f.doRequest(httpReq)
}

func (f *Forwarder) deleteExternal(ctx context.Context, endpoint string, req DeleteResourceRequest) error {
	deleteURL, err := url.JoinPath(endpoint, url.PathEscape(req.ResourceID))
	if err != nil {
		return fmt.Errorf("building DELETE URL: %w", err)
	}
	httpReq, err := http.NewRequestWithContext(ctx, http.MethodDelete, deleteURL, nil)
	if err != nil {
		return fmt.Errorf("creating DELETE request: %w", err)
	}
	httpReq.Header.Set(idempotencyKeyHeader, req.EventID)

	return f.doRequest(httpReq)
}

func (f *Forwarder) doRequest(req *http.Request) error {
	resp, err := f.httpClient.Do(req)
	if err != nil {
		return err
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		return nil
	}

	bodyBytes, _ := io.ReadAll(io.LimitReader(resp.Body, maxResponseBodyBytes))
	msg := string(bodyBytes)
	if msg == "" {
		msg = resp.Status
	}
	return &SPResponseError{StatusCode: resp.StatusCode, Message: msg}
}

// ForwardParams holds the parameters for a single SP forward operation.
type ForwardParams struct {
	ResourceID  string
	ServiceType string
	Spec        json.RawMessage
	EventID     string
	IsCreate    bool
}

// ForwardToSP forwards a single create or delete operation to the given SP.
// This is a pure forward helper — callers own retry, error, and ack policy.
func ForwardToSP(ctx context.Context, fwd SPForwarder, sp *store.StoredProvider, params ForwardParams) error {
	embedded := sp.Type == "embedded"
	if params.IsCreate {
		return fwd.CreateResource(ctx, sp.Endpoint, embedded, CreateResourceRequest{
			ResourceID:  params.ResourceID,
			ServiceType: params.ServiceType,
			Spec:        params.Spec,
			EventID:     params.EventID,
		})
	}
	return fwd.DeleteResource(ctx, sp.Endpoint, embedded, DeleteResourceRequest{
		ResourceID:  params.ResourceID,
		ServiceType: params.ServiceType,
		EventID:     params.EventID,
	})
}

// ForwardRetryPolicy bounds provider call retries.
type ForwardRetryPolicy struct {
	MaxAttempts int
	Backoff     time.Duration
	MaxBackoff  time.Duration
}

// ForwardWithRetry dispatches to a provider using the shared bounded retry policy.
// It returns nil on success, a context error on cancellation, or the final
// provider error after a non-retryable response or exhausted retries.
func ForwardWithRetry(ctx context.Context, forwarder SPForwarder, sp *store.StoredProvider, params ForwardParams, policy ForwardRetryPolicy, logger *slog.Logger) error {
	maxAttempts := policy.MaxAttempts
	if maxAttempts < 1 {
		maxAttempts = 1
	}

	var forwardErr error
	for attempt := 0; attempt < maxAttempts; attempt++ {
		forwardErr = ForwardToSP(ctx, forwarder, sp, params)
		if forwardErr == nil {
			return nil
		}
		if ctx.Err() != nil {
			return ctx.Err()
		}
		if !IsRetryable(forwardErr) {
			return forwardErr
		}
		if attempt < maxAttempts-1 {
			logger.Warn("SP call failed, retrying", append([]any{
				"resource_id", params.ResourceID, "service_type", params.ServiceType,
				"attempt", attempt + 1, "max_attempts", maxAttempts,
				"ce_id", params.EventID, "provider_id", sp.ID,
			}, SafeErrorAttrs(forwardErr)...)...)
			timer := time.NewTimer(backoff.ApplyJitter(
				backoff.CalculateBackoff(policy.Backoff, policy.MaxBackoff, attempt),
				rand.Float64,
			))
			select {
			case <-ctx.Done():
				timer.Stop()
				return ctx.Err()
			case <-timer.C:
			}
		}
	}
	return forwardErr
}
